<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsPublishable>false</IsPublishable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoWarn>$(NoWarn);CA1515;CA1861;CA1707;CA1062;CA1305;S101;CA1054;CA1812;S1144;S1481;S1135;S125</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="coverlet.collector">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Shouldly" />
    <PackageReference Include="AutoFixture" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Modules\Analytics\Modules.Analytics\Modules.Analytics.csproj" />
    <ProjectReference Include="..\..\Modules\Analytics\Modules.Analytics.Contracts\Modules.Analytics.Contracts.csproj" />
    <ProjectReference Include="..\..\Modules\WorkItems\Modules.WorkItems\Modules.WorkItems.csproj" />
  </ItemGroup>
</Project>
