using Finbuckle.MultiTenant.Abstractions;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Options;
using NSubstitute;
using YH.Framework.Shared.Multitenancy;
using YH.Framework.Shared.Persistence;
using YH.Modules.Workspace.Contracts.v1.Workspaces.CreateWorkspace;
using YH.Modules.Workspace.Data;
using YH.Modules.Workspace.Features.v1.Workspaces.CreateWorkspace;
using YH.Modules.Workspace.Services;
using WorkspaceEntity = YH.Modules.Workspace.Domain.Workspace;

namespace YH.Tests.Workspace.Integration;

/// <summary>
/// Integration tests for D-07 — slug uniqueness + collision-retry across the
/// <see cref="SlugGenerator"/> + <see cref="CreateWorkspaceCommandHandler"/> boundary
/// (plan 02-04 Task 2).
/// </summary>
/// <remarks>
/// Two workspaces with the same name must get distinct slugs — the first gets the base slug
/// (<c>acme</c>), the second gets a suffixed one (<c>acme-{suffix}</c>) because the
/// <see cref="SlugGenerator"/> collision probe detects the existing row and appends a random
/// suffix (5-attempt retry contract).
/// </remarks>
public sealed class SlugUniqueTests
{
    [Fact]
    public async Task Create_TwoWorkspacesSameName_SecondGetsSuffixedSlug()
    {
        await using var db = NewInMemoryContext();
        var gen = new SlugGenerator(db);
        var handler = new CreateWorkspaceCommandHandler(db, gen);

        var first = await handler.Handle(new CreateWorkspaceCommand
        {
            Name = "Acme",
            OwnerUserId = Guid.NewGuid(),
        }, CancellationToken.None);
        first.Slug.ShouldBe("acme");

        var second = await handler.Handle(new CreateWorkspaceCommand
        {
            Name = "Acme",
            OwnerUserId = Guid.NewGuid(),
        }, CancellationToken.None);

        // Second slug must differ and follow the acme-{suffix} pattern.
        second.Slug.ShouldNotBe("acme");
        second.Slug.ShouldStartWith("acme-");
        second.Slug.Length.ShouldBeGreaterThan("acme-".Length);

        // Two distinct workspaces + two distinct memberships.
        var workspaces = await db.Workspaces.ToListAsync();
        workspaces.Count.ShouldBe(2);
        workspaces.Select(w => w.Slug).Distinct().Count().ShouldBe(2);
    }

    [Fact]
    public async Task Create_MultipleWorkspacesSameName_AllGetDistinctSlugs()
    {
        await using var db = NewInMemoryContext();
        var gen = new SlugGenerator(db);
        var handler = new CreateWorkspaceCommandHandler(db, gen);

        var slugs = new List<string>();
        for (var i = 0; i < 5; i++)
        {
            var result = await handler.Handle(new CreateWorkspaceCommand
            {
                Name = "Acme",
                OwnerUserId = Guid.NewGuid(),
            }, CancellationToken.None);
            slugs.Add(result.Slug);
        }

        // All 5 slugs must be distinct (1 base + 4 suffixed).
        slugs.Distinct().Count().ShouldBe(5);
        // First is the bare base; the rest have the acme- prefix.
        slugs[0].ShouldBe("acme");
        foreach (var slug in slugs.Skip(1))
        {
            slug.ShouldStartWith("acme-");
        }
    }

    [Fact]
    public async Task Create_AutoGeneratedSlug_IsValidFormat()
    {
        await using var db = NewInMemoryContext();
        var gen = new SlugGenerator(db);
        var handler = new CreateWorkspaceCommandHandler(db, gen);

        // Pre-seed "acme" so generation appends a suffix.
        db.Workspaces.Add(WorkspaceEntity.Create("Acme", "acme", Guid.NewGuid()));
        await db.SaveChangesAsync();

        var result = await handler.Handle(new CreateWorkspaceCommand
        {
            Name = "Acme",
            OwnerUserId = Guid.NewGuid(),
        }, CancellationToken.None);

        gen.IsValidSlug(result.Slug).ShouldBeTrue();
    }

    // ─────────────────────────────────────────────────────────────────────────────
    // Helpers
    // ─────────────────────────────────────────────────────────────────────────────

    private static WorkspaceDbContext NewInMemoryContext()
    {
        var accessor = Substitute.For<IMultiTenantContextAccessor<AppTenantInfo>>();
        var tenant = new AppTenantInfo(Guid.NewGuid().ToString(), "acme-test", "Acme Test");
        accessor.MultiTenantContext.Returns(new MultiTenantContext<AppTenantInfo>(tenant));

        var options = new DbContextOptionsBuilder<WorkspaceDbContext>()
            .UseInMemoryDatabase($"ws-slugunique-{Guid.NewGuid()}")
            .Options;
        var databaseOptions = Options.Create(new DatabaseOptions { Provider = "inmemory" });
        var environment = Substitute.For<IHostEnvironment>();
        environment.EnvironmentName.Returns(Environments.Development);

        return new WorkspaceDbContext(accessor, options, databaseOptions, environment);
    }
}
