// FLOW: Mock data layer for workspace/project UI development (per D-P15-12)
import type {
  IProject,
  IState,
  IWorkspace,
  IWorkspaceMember,
  IIssueLabel,
  TIssue,
  TIssueActivity,
  TIssueComment,
} from "@plane/types";
import { EUserPermissions } from "@plane/types";
import type { TProjectBaseActivity } from "@plane/types";

// ---------------------------------------------------------------------------
// Workspaces
// ---------------------------------------------------------------------------

export const MOCK_WORKSPACES: IWorkspace[] = [
  {
    id: "ws-1",
    name: "Flow 开发组",
    slug: "flow-dev",
    role: EUserPermissions.ADMIN,
    total_members: 5,
    total_projects: 3,
    owner: {
      id: "user-1",
      avatar_url: "",
      display_name: "Admin",
      first_name: "Admin",
      last_name: "",
      is_bot: false,
    } as IWorkspace["owner"],
    created_at: new Date("2026-01-15"),
    updated_at: new Date("2026-06-28"),
    url: "",
    logo_url: null,
    created_by: "user-1",
    updated_by: "user-1",
    organization_size: "10-50",
    timezone: "Asia/Shanghai",
  },
  {
    id: "ws-2",
    name: "个人空间",
    slug: "personal",
    role: EUserPermissions.MEMBER,
    total_members: 2,
    total_projects: 1,
    owner: {
      id: "user-2",
      avatar_url: "",
      display_name: "User",
      first_name: "User",
      last_name: "",
      is_bot: false,
    } as IWorkspace["owner"],
    created_at: new Date("2026-03-01"),
    updated_at: new Date("2026-06-20"),
    url: "",
    logo_url: null,
    created_by: "user-2",
    updated_by: "user-2",
    organization_size: "1-10",
    timezone: "Asia/Shanghai",
  },
];

// ---------------------------------------------------------------------------
// Projects
// ---------------------------------------------------------------------------

const makeLogoProps = (emojiCode: string) => ({
  in_use: "emoji" as const,
  emoji: { value: emojiCode },
});

export const MOCK_PROJECTS: IProject[] = [
  {
    id: "proj-1",
    name: "Flow 前端",
    identifier: "FF",
    logo_props: makeLogoProps("128640"),
    member_role: EUserPermissions.ADMIN,
    workspace: MOCK_WORKSPACES[0].id,
    sort_order: 1,
    archived_at: null,
    cycle_view: true,
    issue_views_view: true,
    module_view: true,
    page_view: true,
    inbox_view: true,
    created_at: new Date("2026-01-20"),
    updated_at: new Date("2026-06-28"),
    created_by: "user-1",
    updated_by: "user-1",
    description: "Flow 前端项目 — React + Vite + Tailwind CSS",
    is_favorite: true,
  },
  {
    id: "proj-2",
    name: "Flow API",
    identifier: "FA",
    logo_props: makeLogoProps("128187"),
    member_role: EUserPermissions.ADMIN,
    workspace: MOCK_WORKSPACES[0].id,
    sort_order: 2,
    archived_at: null,
    cycle_view: true,
    issue_views_view: true,
    module_view: true,
    page_view: true,
    inbox_view: true,
    created_at: new Date("2026-02-01"),
    updated_at: new Date("2026-06-27"),
    created_by: "user-1",
    updated_by: "user-1",
    description: "Flow API — .NET 10 Modular Monolith",
  },
  {
    id: "proj-3",
    name: "Flow 文档",
    identifier: "FD",
    logo_props: makeLogoProps("128214"),
    member_role: EUserPermissions.MEMBER,
    workspace: MOCK_WORKSPACES[0].id,
    sort_order: 3,
    archived_at: null,
    cycle_view: false,
    issue_views_view: false,
    module_view: false,
    page_view: true,
    inbox_view: false,
    created_at: new Date("2026-03-10"),
    updated_at: new Date("2026-06-25"),
    created_by: "user-1",
    updated_by: "user-2",
    description: "项目文档和 Wiki",
  },
  {
    id: "proj-4",
    name: "个人笔记",
    identifier: "PN",
    logo_props: makeLogoProps("128221"),
    member_role: EUserPermissions.MEMBER,
    workspace: MOCK_WORKSPACES[1].id,
    sort_order: 1,
    archived_at: null,
    cycle_view: false,
    issue_views_view: false,
    module_view: false,
    page_view: true,
    inbox_view: false,
    created_at: new Date("2026-03-05"),
    updated_at: new Date("2026-06-20"),
    created_by: "user-2",
    updated_by: "user-2",
    description: "个人笔记和待办事项",
  },
];

// ---------------------------------------------------------------------------
// Members
// ---------------------------------------------------------------------------

export const MOCK_MEMBERS: Record<string, IWorkspaceMember[]> = {
  "ws-1": [
    {
      id: "mem-1",
      member: {
        id: "user-1",
        avatar_url: "",
        display_name: "张三",
        first_name: "张三",
        last_name: "",
        is_bot: false,
      },
      role: EUserPermissions.ADMIN,
      email: "zhangsan@example.com",
    },
    {
      id: "mem-2",
      member: {
        id: "user-2",
        avatar_url: "",
        display_name: "李四",
        first_name: "李四",
        last_name: "",
        is_bot: false,
      },
      role: EUserPermissions.MEMBER,
      email: "lisi@example.com",
    },
    {
      id: "mem-3",
      member: {
        id: "user-3",
        avatar_url: "",
        display_name: "王五",
        first_name: "王五",
        last_name: "",
        is_bot: false,
      },
      role: EUserPermissions.MEMBER,
      email: "wangwu@example.com",
    },
    {
      id: "mem-4",
      member: {
        id: "user-4",
        avatar_url: "",
        display_name: "赵六",
        first_name: "赵六",
        last_name: "",
        is_bot: false,
      },
      role: EUserPermissions.GUEST,
      email: "zhaoliu@example.com",
    },
    {
      id: "mem-5",
      member: {
        id: "user-5",
        avatar_url: "",
        display_name: "陈七",
        first_name: "陈七",
        last_name: "",
        is_bot: false,
      },
      role: EUserPermissions.MEMBER,
      email: "chenqi@example.com",
    },
  ],
  "ws-2": [
    {
      id: "mem-6",
      member: {
        id: "user-2",
        avatar_url: "",
        display_name: "李四",
        first_name: "李四",
        last_name: "",
        is_bot: false,
      },
      role: EUserPermissions.ADMIN,
      email: "lisi@example.com",
    },
    {
      id: "mem-7",
      member: {
        id: "user-6",
        avatar_url: "",
        display_name: "周八",
        first_name: "周八",
        last_name: "",
        is_bot: false,
      },
      role: EUserPermissions.MEMBER,
      email: "zhouba@example.com",
    },
  ],
};

// ---------------------------------------------------------------------------
// Activities
// ---------------------------------------------------------------------------

const now = Date.now();
const dayMs = 86400 * 1000;

export const MOCK_ACTIVITIES: TProjectBaseActivity[] = [
  {
    id: "act-1",
    field: "name",
    epoch: now,
    verb: "created",
    comment: undefined,
    old_value: undefined,
    new_value: undefined,
    old_identifier: undefined,
    new_identifier: undefined,
    actor: "user-1",
    created_at: new Date(now).toISOString(),
    updated_at: new Date(now).toISOString(),
    workspace: "ws-1",
    project: "proj-1",
  },
  {
    id: "act-2",
    field: "state",
    epoch: now - dayMs * 1,
    verb: "updated",
    comment: undefined,
    old_value: "backlog",
    new_value: "in_progress",
    old_identifier: undefined,
    new_identifier: undefined,
    actor: "user-2",
    created_at: new Date(now - dayMs * 1).toISOString(),
    updated_at: new Date(now - dayMs * 1).toISOString(),
    workspace: "ws-1",
    project: "proj-1",
  },
  {
    id: "act-3",
    field: "assignee",
    epoch: now - dayMs * 2,
    verb: "updated",
    comment: undefined,
    old_value: "",
    new_value: "user-3",
    old_identifier: undefined,
    new_identifier: undefined,
    actor: "user-1",
    created_at: new Date(now - dayMs * 2).toISOString(),
    updated_at: new Date(now - dayMs * 2).toISOString(),
    workspace: "ws-1",
    project: "proj-2",
  },
  {
    id: "act-4",
    field: "description",
    epoch: now - dayMs * 3,
    verb: "created",
    comment: "添加了新的 API 文档",
    old_value: undefined,
    new_value: undefined,
    old_identifier: undefined,
    new_identifier: undefined,
    actor: "user-1",
    created_at: new Date(now - dayMs * 3).toISOString(),
    updated_at: new Date(now - dayMs * 3).toISOString(),
    workspace: "ws-1",
    project: "proj-2",
  },
  {
    id: "act-5",
    field: "name",
    epoch: now - dayMs * 5,
    verb: "created",
    comment: undefined,
    old_value: undefined,
    new_value: undefined,
    old_identifier: undefined,
    new_identifier: undefined,
    actor: "user-2",
    created_at: new Date(now - dayMs * 5).toISOString(),
    updated_at: new Date(now - dayMs * 5).toISOString(),
    workspace: "ws-2",
    project: "proj-4",
  },
  {
    id: "act-6",
    field: "priority",
    epoch: now - dayMs * 7,
    verb: "updated",
    comment: undefined,
    old_value: "low",
    new_value: "urgent",
    old_identifier: undefined,
    new_identifier: undefined,
    actor: "user-2",
    created_at: new Date(now - dayMs * 7).toISOString(),
    updated_at: new Date(now - dayMs * 7).toISOString(),
    workspace: "ws-2",
    project: "proj-4",
  },
  {
    id: "act-7",
    field: "state",
    epoch: now - dayMs * 10,
    verb: "updated",
    comment: undefined,
    old_value: "in_progress",
    new_value: "done",
    old_identifier: undefined,
    new_identifier: undefined,
    actor: "user-1",
    created_at: new Date(now - dayMs * 10).toISOString(),
    updated_at: new Date(now - dayMs * 10).toISOString(),
    workspace: "ws-1",
    project: "proj-1",
  },
  {
    id: "act-8",
    field: "name",
    epoch: now - dayMs * 14,
    verb: "created",
    comment: undefined,
    old_value: undefined,
    new_value: undefined,
    old_identifier: undefined,
    new_identifier: undefined,
    actor: "user-1",
    created_at: new Date(now - dayMs * 14).toISOString(),
    updated_at: new Date(now - dayMs * 14).toISOString(),
    workspace: "ws-1",
    project: "proj-3",
  },
];

// ---------------------------------------------------------------------------
// States (per D-P16-03: extend with project states)
// ---------------------------------------------------------------------------

export const MOCK_STATES: IState[] = [
  {
    id: "state-ff-1",
    color: "#9CA3AF",
    default: true,
    description: "",
    group: "backlog",
    name: "待办",
    project_id: "proj-1",
    sequence: 1,
    workspace_id: "ws-1",
    order: 1,
  },
  {
    id: "state-ff-2",
    color: "#6B7280",
    default: false,
    description: "",
    group: "unstarted",
    name: "未开始",
    project_id: "proj-1",
    sequence: 2,
    workspace_id: "ws-1",
    order: 2,
  },
  {
    id: "state-ff-3",
    color: "#F59E0B",
    default: false,
    description: "",
    group: "started",
    name: "进行中",
    project_id: "proj-1",
    sequence: 3,
    workspace_id: "ws-1",
    order: 3,
  },
  {
    id: "state-ff-4",
    color: "#10B981",
    default: false,
    description: "",
    group: "completed",
    name: "已完成",
    project_id: "proj-1",
    sequence: 4,
    workspace_id: "ws-1",
    order: 4,
  },
  {
    id: "state-ff-5",
    color: "#EF4444",
    default: false,
    description: "",
    group: "cancelled",
    name: "已取消",
    project_id: "proj-1",
    sequence: 5,
    workspace_id: "ws-1",
    order: 5,
  },
  {
    id: "state-fa-1",
    color: "#9CA3AF",
    default: true,
    description: "",
    group: "backlog",
    name: "待办",
    project_id: "proj-2",
    sequence: 1,
    workspace_id: "ws-1",
    order: 1,
  },
  {
    id: "state-fa-2",
    color: "#6B7280",
    default: false,
    description: "",
    group: "unstarted",
    name: "未开始",
    project_id: "proj-2",
    sequence: 2,
    workspace_id: "ws-1",
    order: 2,
  },
  {
    id: "state-fa-3",
    color: "#F59E0B",
    default: false,
    description: "",
    group: "started",
    name: "开发中",
    project_id: "proj-2",
    sequence: 3,
    workspace_id: "ws-1",
    order: 3,
  },
  {
    id: "state-fa-4",
    color: "#3B82F6",
    default: false,
    description: "",
    group: "started",
    name: "测试中",
    project_id: "proj-2",
    sequence: 4,
    workspace_id: "ws-1",
    order: 4,
  },
  {
    id: "state-fa-5",
    color: "#10B981",
    default: false,
    description: "",
    group: "completed",
    name: "已完成",
    project_id: "proj-2",
    sequence: 5,
    workspace_id: "ws-1",
    order: 5,
  },
  {
    id: "state-fa-6",
    color: "#EF4444",
    default: false,
    description: "",
    group: "cancelled",
    name: "已取消",
    project_id: "proj-2",
    sequence: 6,
    workspace_id: "ws-1",
    order: 6,
  },
  {
    id: "state-fd-1",
    color: "#9CA3AF",
    default: true,
    description: "",
    group: "backlog",
    name: "待办",
    project_id: "proj-3",
    sequence: 1,
    workspace_id: "ws-1",
    order: 1,
  },
  {
    id: "state-fd-2",
    color: "#6B7280",
    default: false,
    description: "",
    group: "unstarted",
    name: "未开始",
    project_id: "proj-3",
    sequence: 2,
    workspace_id: "ws-1",
    order: 2,
  },
  {
    id: "state-fd-3",
    color: "#F59E0B",
    default: false,
    description: "",
    group: "started",
    name: "编写中",
    project_id: "proj-3",
    sequence: 3,
    workspace_id: "ws-1",
    order: 3,
  },
  {
    id: "state-fd-4",
    color: "#10B981",
    default: false,
    description: "",
    group: "completed",
    name: "已完成",
    project_id: "proj-3",
    sequence: 4,
    workspace_id: "ws-1",
    order: 4,
  },
  {
    id: "state-fd-5",
    color: "#EF4444",
    default: false,
    description: "",
    group: "cancelled",
    name: "已取消",
    project_id: "proj-3",
    sequence: 5,
    workspace_id: "ws-1",
    order: 5,
  },
];

// ---------------------------------------------------------------------------
// Labels (per D-P16-03)
// ---------------------------------------------------------------------------

export const MOCK_LABELS: IIssueLabel[] = [
  {
    id: "label-1",
    name: "Bug",
    color: "#EF4444",
    project_id: "proj-1",
    workspace_id: "ws-1",
    parent: null,
    sort_order: 1,
  },
  {
    id: "label-2",
    name: "增强",
    color: "#3B82F6",
    project_id: "proj-1",
    workspace_id: "ws-1",
    parent: null,
    sort_order: 2,
  },
  {
    id: "label-3",
    name: "UI",
    color: "#8B5CF6",
    project_id: "proj-1",
    workspace_id: "ws-1",
    parent: null,
    sort_order: 3,
  },
  {
    id: "label-4",
    name: "性能",
    color: "#F59E0B",
    project_id: "proj-1",
    workspace_id: "ws-1",
    parent: null,
    sort_order: 4,
  },
  {
    id: "label-5",
    name: "文档",
    color: "#10B981",
    project_id: "proj-1",
    workspace_id: "ws-1",
    parent: null,
    sort_order: 5,
  },
  {
    id: "label-6",
    name: "安全",
    color: "#EC4899",
    project_id: "proj-1",
    workspace_id: "ws-1",
    parent: null,
    sort_order: 6,
  },
  {
    id: "label-7",
    name: "Bug",
    color: "#EF4444",
    project_id: "proj-2",
    workspace_id: "ws-1",
    parent: null,
    sort_order: 1,
  },
  {
    id: "label-8",
    name: "API",
    color: "#3B82F6",
    project_id: "proj-2",
    workspace_id: "ws-1",
    parent: null,
    sort_order: 2,
  },
  {
    id: "label-9",
    name: "数据库",
    color: "#10B981",
    project_id: "proj-2",
    workspace_id: "ws-1",
    parent: null,
    sort_order: 3,
  },
  {
    id: "label-10",
    name: "单元测试",
    color: "#8B5CF6",
    project_id: "proj-2",
    workspace_id: "ws-1",
    parent: null,
    sort_order: 4,
  },
];

// ---------------------------------------------------------------------------
// Issues (per D-P16-03: 17 mock issues across 3 projects)
// ---------------------------------------------------------------------------

export const MOCK_ISSUES: TIssue[] = [
  {
    id: "issue-1",
    sequence_id: 1,
    name: "实现用户登录页面 UI",
    sort_order: 1,
    state_id: "state-ff-1",
    priority: "high",
    label_ids: ["label-3", "label-2"],
    assignee_ids: ["user-1", "user-2"],
    estimate_point: "5",
    sub_issues_count: 0,
    attachment_count: 0,
    link_count: 0,
    project_id: "proj-1",
    parent_id: null,
    cycle_id: null,
    module_ids: null,
    type_id: null,
    created_at: new Date(now - dayMs * 3).toISOString(),
    updated_at: new Date(now - dayMs * 1).toISOString(),
    start_date: null,
    target_date: new Date(now + dayMs * 7).toISOString(),
    completed_at: null,
    archived_at: null,
    created_by: "user-1",
    updated_by: "user-2",
    is_draft: false,
    description_html: "<p>实现用户登录页面，包括邮箱密码输入框和登录按钮</p>",
  },
  {
    id: "issue-2",
    sequence_id: 2,
    name: "集成 JWT 认证流程",
    sort_order: 2,
    state_id: "state-ff-3",
    priority: "urgent",
    label_ids: ["label-4", "label-6"],
    assignee_ids: ["user-1"],
    estimate_point: "8",
    sub_issues_count: 2,
    attachment_count: 0,
    link_count: 0,
    project_id: "proj-1",
    parent_id: null,
    cycle_id: null,
    module_ids: null,
    type_id: null,
    created_at: new Date(now - dayMs * 5).toISOString(),
    updated_at: new Date(now - dayMs * 2).toISOString(),
    start_date: new Date(now - dayMs * 2).toISOString(),
    target_date: new Date(now + dayMs * 3).toISOString(),
    completed_at: null,
    archived_at: null,
    created_by: "user-1",
    updated_by: "user-1",
    is_draft: false,
    description_html:
      "<p>集成 JWT 认证，包括 token 刷新和自动重试</p><ul><li>登录接口对接</li><li>Token 刷新逻辑</li><li>自动重试拦截器</li></ul>",
  },
  {
    id: "issue-3",
    sequence_id: 3,
    name: "修复表单验证错误提示不显示问题",
    sort_order: 3,
    state_id: "state-ff-5",
    priority: "medium",
    label_ids: ["label-1"],
    assignee_ids: ["user-2"],
    estimate_point: "3",
    sub_issues_count: 0,
    attachment_count: 0,
    link_count: 0,
    project_id: "proj-1",
    parent_id: null,
    cycle_id: null,
    module_ids: null,
    type_id: null,
    created_at: new Date(now - dayMs * 7).toISOString(),
    updated_at: new Date(now - dayMs * 4).toISOString(),
    start_date: null,
    target_date: null,
    completed_at: null,
    archived_at: new Date(now).toISOString(),
    created_by: "user-2",
    updated_by: "user-2",
    is_draft: false,
  },
  {
    id: "issue-4",
    sequence_id: 4,
    name: "优化首页加载性能",
    sort_order: 4,
    state_id: "state-ff-2",
    priority: "low",
    label_ids: ["label-4"],
    assignee_ids: [],
    estimate_point: "13",
    sub_issues_count: 0,
    attachment_count: 0,
    link_count: 0,
    project_id: "proj-1",
    parent_id: null,
    cycle_id: null,
    module_ids: null,
    type_id: null,
    created_at: new Date(now - dayMs * 10).toISOString(),
    updated_at: new Date(now - dayMs * 8).toISOString(),
    start_date: null,
    target_date: new Date(now + dayMs * 14).toISOString(),
    completed_at: null,
    archived_at: null,
    created_by: "user-1",
    updated_by: "user-1",
    is_draft: false,
    description_html: "<p>首页加载时间超过 3 秒，需要优化组件懒加载和数据请求策略</p>",
  },
  {
    id: "issue-5",
    sequence_id: 5,
    name: "添加暗色模式支持",
    sort_order: 5,
    state_id: "state-ff-3",
    priority: "high",
    label_ids: ["label-3", "label-2"],
    assignee_ids: ["user-3"],
    estimate_point: "21",
    sub_issues_count: 3,
    attachment_count: 0,
    link_count: 0,
    project_id: "proj-1",
    parent_id: null,
    cycle_id: null,
    module_ids: null,
    type_id: null,
    created_at: new Date(now - dayMs * 14).toISOString(),
    updated_at: new Date(now - dayMs * 1).toISOString(),
    start_date: new Date(now - dayMs * 5).toISOString(),
    target_date: new Date(now + dayMs * 21).toISOString(),
    completed_at: null,
    archived_at: null,
    created_by: "user-3",
    updated_by: "user-3",
    is_draft: false,
    description_html: "<p>实现暗色模式切换功能，所有组件需要支持主题切换</p>",
  },
  {
    id: "issue-6",
    sequence_id: 6,
    name: "编写用户注册页面 E2E 测试",
    sort_order: 6,
    state_id: "state-ff-4",
    priority: "medium",
    label_ids: ["label-2"],
    assignee_ids: ["user-4"],
    estimate_point: "5",
    sub_issues_count: 0,
    attachment_count: 0,
    link_count: 0,
    project_id: "proj-1",
    parent_id: null,
    cycle_id: null,
    module_ids: null,
    type_id: null,
    created_at: new Date(now - dayMs * 6).toISOString(),
    updated_at: new Date(now - dayMs * 1).toISOString(),
    start_date: null,
    target_date: null,
    completed_at: new Date(now - dayMs * 1).toISOString(),
    archived_at: null,
    created_by: "user-1",
    updated_by: "user-1",
    is_draft: false,
  },
  {
    id: "issue-7",
    sequence_id: 7,
    name: "重构通知模块状态管理",
    sort_order: 7,
    state_id: "state-ff-3",
    priority: "low",
    label_ids: ["label-4"],
    assignee_ids: ["user-1", "user-2"],
    estimate_point: "13",
    sub_issues_count: 0,
    attachment_count: 0,
    link_count: 0,
    project_id: "proj-1",
    parent_id: null,
    cycle_id: null,
    module_ids: null,
    type_id: null,
    created_at: new Date(now - dayMs * 2).toISOString(),
    updated_at: new Date(now - dayMs * 1).toISOString(),
    start_date: null,
    target_date: null,
    completed_at: null,
    archived_at: null,
    created_by: "user-2",
    updated_by: "user-2",
    is_draft: false,
    description_html: "<p>通知模块当前使用 MobX store，需要迁移到 TanStack Query</p>",
  },
  {
    id: "issue-8",
    sequence_id: 1,
    name: "设计 Issue 数据模型",
    sort_order: 1,
    state_id: "state-fa-4",
    priority: "urgent",
    label_ids: ["label-8", "label-9"],
    assignee_ids: ["user-1"],
    estimate_point: "8",
    sub_issues_count: 2,
    attachment_count: 0,
    link_count: 0,
    project_id: "proj-2",
    parent_id: null,
    cycle_id: null,
    module_ids: null,
    type_id: null,
    created_at: new Date(now - dayMs * 15).toISOString(),
    updated_at: new Date(now - dayMs * 3).toISOString(),
    start_date: new Date(now - dayMs * 10).toISOString(),
    target_date: new Date(now - dayMs * 2).toISOString(),
    completed_at: null,
    archived_at: null,
    created_by: "user-1",
    updated_by: "user-3",
    is_draft: false,
    description_html: "<p>设计 Issue 数据的数据库模型和 API 接口定义</p><p>包括状态机、优先级、标签等字段</p>",
  },
  {
    id: "issue-9",
    sequence_id: 2,
    name: "实现 Issue CRUD API 端点",
    sort_order: 2,
    state_id: "state-fa-3",
    priority: "high",
    label_ids: ["label-8"],
    assignee_ids: ["user-3"],
    estimate_point: "13",
    sub_issues_count: 3,
    attachment_count: 0,
    link_count: 0,
    project_id: "proj-2",
    parent_id: null,
    cycle_id: null,
    module_ids: null,
    type_id: null,
    created_at: new Date(now - dayMs * 12).toISOString(),
    updated_at: new Date(now).toISOString(),
    start_date: new Date(now - dayMs * 8).toISOString(),
    target_date: new Date(now + dayMs * 5).toISOString(),
    completed_at: null,
    archived_at: null,
    created_by: "user-3",
    updated_by: "user-3",
    is_draft: false,
    description_html: "<p>实现 Issue 的增删查改 API，包括分页和筛选支持</p>",
  },
  {
    id: "issue-10",
    sequence_id: 3,
    name: "添加 API 版本控制和文档",
    sort_order: 3,
    state_id: "state-fa-1",
    priority: "medium",
    label_ids: ["label-8", "label-10"],
    assignee_ids: [],
    estimate_point: "5",
    sub_issues_count: 0,
    attachment_count: 0,
    link_count: 0,
    project_id: "proj-2",
    parent_id: null,
    cycle_id: null,
    module_ids: null,
    type_id: null,
    created_at: new Date(now - dayMs * 8).toISOString(),
    updated_at: new Date(now - dayMs * 6).toISOString(),
    start_date: null,
    target_date: new Date(now + dayMs * 14).toISOString(),
    completed_at: null,
    archived_at: null,
    created_by: "user-1",
    updated_by: "user-1",
    is_draft: false,
    description_html: "<p>使用 OpenAPI/Scalar 生成 API 文档，确保版本控制策略</p>",
  },
  {
    id: "issue-11",
    sequence_id: 4,
    name: "修复并发请求导致的死锁问题",
    sort_order: 4,
    state_id: "state-fa-5",
    priority: "urgent",
    label_ids: ["label-7", "label-9"],
    assignee_ids: ["user-1"],
    estimate_point: "13",
    sub_issues_count: 0,
    attachment_count: 0,
    link_count: 0,
    project_id: "proj-2",
    parent_id: null,
    cycle_id: null,
    module_ids: null,
    type_id: null,
    created_at: new Date(now - dayMs * 4).toISOString(),
    updated_at: new Date(now - dayMs * 1).toISOString(),
    start_date: null,
    target_date: null,
    completed_at: new Date(now - dayMs * 1).toISOString(),
    archived_at: null,
    created_by: "user-1",
    updated_by: "user-1",
    is_draft: false,
    description_html: "<p>高并发下数据库连接池死锁，需要优化事务隔离级别</p>",
  },
  {
    id: "issue-12",
    sequence_id: 5,
    name: "实现缓存层（Redis）",
    sort_order: 5,
    state_id: "state-fa-2",
    priority: "high",
    label_ids: ["label-8", "label-4"],
    assignee_ids: ["user-3"],
    estimate_point: "8",
    sub_issues_count: 0,
    attachment_count: 0,
    link_count: 0,
    project_id: "proj-2",
    parent_id: null,
    cycle_id: null,
    module_ids: null,
    type_id: null,
    created_at: new Date(now - dayMs * 6).toISOString(),
    updated_at: new Date(now - dayMs * 2).toISOString(),
    start_date: new Date(now - dayMs * 3).toISOString(),
    target_date: new Date(now + dayMs * 10).toISOString(),
    completed_at: null,
    archived_at: null,
    created_by: "user-3",
    updated_by: "user-3",
    is_draft: false,
    description_html: "<p>实现 Redis 缓存层，缓存热点数据减少数据库压力</p>",
  },
  {
    id: "issue-13",
    sequence_id: 6,
    name: "为 API 添加请求速率限制",
    sort_order: 6,
    state_id: "state-fa-6",
    priority: "medium",
    label_ids: ["label-7", "label-8"],
    assignee_ids: ["user-1"],
    estimate_point: "5",
    sub_issues_count: 0,
    attachment_count: 0,
    link_count: 0,
    project_id: "proj-2",
    parent_id: null,
    cycle_id: null,
    module_ids: null,
    type_id: null,
    created_at: new Date(now - dayMs * 9).toISOString(),
    updated_at: new Date(now - dayMs * 7).toISOString(),
    start_date: null,
    target_date: null,
    completed_at: null,
    archived_at: new Date(now).toISOString(),
    created_by: "user-1",
    updated_by: "user-1",
    is_draft: false,
  },
  {
    id: "issue-14",
    sequence_id: 7,
    name: "编写单元测试覆盖核心业务逻辑",
    sort_order: 7,
    state_id: "state-fa-1",
    priority: "low",
    label_ids: ["label-10"],
    assignee_ids: ["user-5"],
    estimate_point: "21",
    sub_issues_count: 0,
    attachment_count: 0,
    link_count: 0,
    project_id: "proj-2",
    parent_id: null,
    cycle_id: null,
    module_ids: null,
    type_id: null,
    created_at: new Date(now - dayMs * 11).toISOString(),
    updated_at: new Date(now - dayMs * 9).toISOString(),
    start_date: null,
    target_date: new Date(now + dayMs * 30).toISOString(),
    completed_at: null,
    archived_at: null,
    created_by: "user-5",
    updated_by: "user-5",
    is_draft: false,
  },
  {
    id: "issue-15",
    sequence_id: 1,
    name: "编写项目架构设计文档",
    sort_order: 1,
    state_id: "state-fd-4",
    priority: "high",
    label_ids: ["label-5"],
    assignee_ids: ["user-1"],
    estimate_point: "3",
    sub_issues_count: 0,
    attachment_count: 0,
    link_count: 0,
    project_id: "proj-3",
    parent_id: null,
    cycle_id: null,
    module_ids: null,
    type_id: null,
    created_at: new Date(now - dayMs * 20).toISOString(),
    updated_at: new Date(now - dayMs * 10).toISOString(),
    start_date: null,
    target_date: null,
    completed_at: new Date(now - dayMs * 10).toISOString(),
    archived_at: null,
    created_by: "user-1",
    updated_by: "user-1",
    is_draft: false,
    description_html: "<p>编写完整的项目架构设计文档，包括系统架构图、数据流图、技术选型说明</p>",
  },
  {
    id: "issue-16",
    sequence_id: 2,
    name: "撰写 API 集成指南",
    sort_order: 2,
    state_id: "state-fd-3",
    priority: "medium",
    label_ids: ["label-5"],
    assignee_ids: ["user-2"],
    estimate_point: "5",
    sub_issues_count: 0,
    attachment_count: 0,
    link_count: 0,
    project_id: "proj-3",
    parent_id: null,
    cycle_id: null,
    module_ids: null,
    type_id: null,
    created_at: new Date(now - dayMs * 12).toISOString(),
    updated_at: new Date(now - dayMs * 6).toISOString(),
    start_date: new Date(now - dayMs * 7).toISOString(),
    target_date: new Date(now + dayMs * 5).toISOString(),
    completed_at: null,
    archived_at: null,
    created_by: "user-2",
    updated_by: "user-2",
    is_draft: false,
    description_html: "<p>撰写面向开发者的 API 集成指南，包含示例代码和最佳实践</p>",
  },
  {
    id: "issue-17",
    sequence_id: 3,
    name: "更新 README 和贡献指南",
    sort_order: 3,
    state_id: "state-fd-1",
    priority: "low",
    label_ids: ["label-5"],
    assignee_ids: [],
    estimate_point: "2",
    sub_issues_count: 0,
    attachment_count: 0,
    link_count: 0,
    project_id: "proj-3",
    parent_id: null,
    cycle_id: null,
    module_ids: null,
    type_id: null,
    created_at: new Date(now - dayMs * 5).toISOString(),
    updated_at: new Date(now - dayMs * 3).toISOString(),
    start_date: null,
    target_date: null,
    completed_at: null,
    archived_at: null,
    created_by: "user-1",
    updated_by: "user-1",
    is_draft: false,
  },
];

// ---------------------------------------------------------------------------
// Issue Comments (per RESEARCH.md — 3-5 comments per issue)
// ---------------------------------------------------------------------------

export const MOCK_ISSUE_COMMENTS: TIssueComment[] = [
  {
    id: "comment-1",
    workspace: "ws-1",
    project: "proj-1",
    issue: "issue-1",
    actor: "user-2",
    actor_detail: {
      id: "user-2",
      first_name: "李四",
      last_name: "",
      avatar_url: "",
      is_bot: false,
      display_name: "李四",
    },
    created_at: new Date(now - dayMs * 2).toISOString(),
    updated_at: new Date(now - dayMs * 2).toISOString(),
    created_by: "user-2",
    updated_by: "user-2",
    attachments: [],
    comment_reactions: [],
    comment_stripped: "好的，我来负责 UI 部分",
    comment_html: "<p>好的，我来负责 UI 部分</p>",
    comment_json: {
      type: "doc",
      content: [{ type: "paragraph", content: [{ type: "text", text: "好的，我来负责 UI 部分" }] }],
    } as any,
    external_id: undefined,
    external_source: undefined,
    access: "INTERNAL" as any,
    workspace_detail: { id: "ws-1", name: "Flow 开发组", slug: "flow-dev" },
    project_detail: {
      id: "proj-1",
      identifier: "FF",
      name: "Flow 前端",
      cover_image: "",
      description: null,
      emoji: null,
      icon_prop: null,
    },
    issue_detail: {
      id: "issue-1",
      sequence_id: 1,
      sort_order: false as any,
      name: "实现用户登录页面 UI",
      description_html: "",
      priority: "high" as any,
      start_date: "",
      target_date: "",
      is_draft: false,
    },
    edited_at: undefined,
  },
  {
    id: "comment-2",
    workspace: "ws-1",
    project: "proj-1",
    issue: "issue-1",
    actor: "user-1",
    actor_detail: {
      id: "user-1",
      first_name: "张三",
      last_name: "",
      avatar_url: "",
      is_bot: false,
      display_name: "张三",
    },
    created_at: new Date(now - dayMs * 1).toISOString(),
    updated_at: new Date(now - dayMs * 1).toISOString(),
    created_by: "user-1",
    updated_by: "user-1",
    attachments: [],
    comment_reactions: [],
    comment_stripped: "我已经完成了登录表单的布局，请 review",
    comment_html: "<p>我已经完成了登录表单的布局，请 review</p>",
    comment_json: {
      type: "doc",
      content: [{ type: "paragraph", content: [{ type: "text", text: "我已经完成了登录表单的布局，请 review" }] }],
    } as any,
    external_id: undefined,
    external_source: undefined,
    access: "INTERNAL" as any,
    workspace_detail: { id: "ws-1", name: "Flow 开发组", slug: "flow-dev" },
    project_detail: {
      id: "proj-1",
      identifier: "FF",
      name: "Flow 前端",
      cover_image: "",
      description: null,
      emoji: null,
      icon_prop: null,
    },
    issue_detail: {
      id: "issue-1",
      sequence_id: 1,
      sort_order: false as any,
      name: "实现用户登录页面 UI",
      description_html: "",
      priority: "high" as any,
      start_date: "",
      target_date: "",
      is_draft: false,
    },
    edited_at: undefined,
  },
  {
    id: "comment-3",
    workspace: "ws-1",
    project: "proj-1",
    issue: "issue-2",
    actor: "user-3",
    actor_detail: {
      id: "user-3",
      first_name: "王五",
      last_name: "",
      avatar_url: "",
      is_bot: false,
      display_name: "王五",
    },
    created_at: new Date(now - dayMs * 3).toISOString(),
    updated_at: new Date(now - dayMs * 2).toISOString(),
    created_by: "user-3",
    updated_by: "user-3",
    attachments: [],
    comment_reactions: [],
    comment_stripped: "JWT 刷新逻辑我建议使用 axios 拦截器实现",
    comment_html: "<p>JWT 刷新逻辑我建议使用 axios 拦截器实现</p>",
    comment_json: {
      type: "doc",
      content: [{ type: "paragraph", content: [{ type: "text", text: "JWT 刷新逻辑我建议使用 axios 拦截器实现" }] }],
    } as any,
    external_id: undefined,
    external_source: undefined,
    access: "INTERNAL" as any,
    workspace_detail: { id: "ws-1", name: "Flow 开发组", slug: "flow-dev" },
    project_detail: {
      id: "proj-1",
      identifier: "FF",
      name: "Flow 前端",
      cover_image: "",
      description: null,
      emoji: null,
      icon_prop: null,
    },
    issue_detail: {
      id: "issue-2",
      sequence_id: 2,
      sort_order: false as any,
      name: "集成 JWT 认证流程",
      description_html: "",
      priority: "urgent" as any,
      start_date: "",
      target_date: "",
      is_draft: false,
    },
    edited_at: new Date(now - dayMs * 2).toISOString(),
  },
  {
    id: "comment-4",
    workspace: "ws-1",
    project: "proj-1",
    issue: "issue-5",
    actor: "user-1",
    actor_detail: {
      id: "user-1",
      first_name: "张三",
      last_name: "",
      avatar_url: "",
      is_bot: false,
      display_name: "张三",
    },
    created_at: new Date(now - dayMs * 5).toISOString(),
    updated_at: new Date(now - dayMs * 5).toISOString(),
    created_by: "user-1",
    updated_by: "user-1",
    attachments: [],
    comment_reactions: [],
    comment_stripped: "暗色模式的配色方案已共享到设计团队，请查收",
    comment_html: "<p>暗色模式的配色方案已共享到设计团队，请查收</p>",
    comment_json: {
      type: "doc",
      content: [{ type: "paragraph", content: [{ type: "text", text: "暗色模式的配色方案已共享到设计团队，请查收" }] }],
    } as any,
    external_id: undefined,
    external_source: undefined,
    access: "INTERNAL" as any,
    workspace_detail: { id: "ws-1", name: "Flow 开发组", slug: "flow-dev" },
    project_detail: {
      id: "proj-1",
      identifier: "FF",
      name: "Flow 前端",
      cover_image: "",
      description: null,
      emoji: null,
      icon_prop: null,
    },
    issue_detail: {
      id: "issue-5",
      sequence_id: 5,
      sort_order: false as any,
      name: "添加暗色模式支持",
      description_html: "",
      priority: "high" as any,
      start_date: "",
      target_date: "",
      is_draft: false,
    },
    edited_at: undefined,
  },
  {
    id: "comment-5",
    workspace: "ws-1",
    project: "proj-1",
    issue: "issue-5",
    actor: "user-3",
    actor_detail: {
      id: "user-3",
      first_name: "王五",
      last_name: "",
      avatar_url: "",
      is_bot: false,
      display_name: "王五",
    },
    created_at: new Date(now - dayMs * 3).toISOString(),
    updated_at: new Date(now - dayMs * 3).toISOString(),
    created_by: "user-3",
    updated_by: "user-3",
    attachments: [],
    comment_reactions: [],
    comment_stripped: "已收到，我会在一周内完成所有组件的适配",
    comment_html: "<p>已收到，我会在一周内完成所有组件的适配</p>",
    comment_json: {
      type: "doc",
      content: [{ type: "paragraph", content: [{ type: "text", text: "已收到，我会在一周内完成所有组件的适配" }] }],
    } as any,
    external_id: undefined,
    external_source: undefined,
    access: "INTERNAL" as any,
    workspace_detail: { id: "ws-1", name: "Flow 开发组", slug: "flow-dev" },
    project_detail: {
      id: "proj-1",
      identifier: "FF",
      name: "Flow 前端",
      cover_image: "",
      description: null,
      emoji: null,
      icon_prop: null,
    },
    issue_detail: {
      id: "issue-5",
      sequence_id: 5,
      sort_order: false as any,
      name: "添加暗色模式支持",
      description_html: "",
      priority: "high" as any,
      start_date: "",
      target_date: "",
      is_draft: false,
    },
    edited_at: undefined,
  },
  {
    id: "comment-6",
    workspace: "ws-1",
    project: "proj-1",
    issue: "issue-7",
    actor: "user-2",
    actor_detail: {
      id: "user-2",
      first_name: "李四",
      last_name: "",
      avatar_url: "",
      is_bot: false,
      display_name: "李四",
    },
    created_at: new Date(now - dayMs * 1).toISOString(),
    updated_at: new Date(now - dayMs * 1).toISOString(),
    created_by: "user-2",
    updated_by: "user-2",
    attachments: [],
    comment_reactions: [],
    comment_stripped: "当前 MobX 和 TanStack Query 数据存在同步问题，需要优先解决",
    comment_html: "<p>当前 MobX 和 TanStack Query 数据存在同步问题，需要优先解决</p>",
    comment_json: {
      type: "doc",
      content: [
        { type: "paragraph", content: [{ type: "text", text: "当前 MobX 和 TanStack Query 数据存在同步问题" }] },
      ],
    } as any,
    external_id: undefined,
    external_source: undefined,
    access: "INTERNAL" as any,
    workspace_detail: { id: "ws-1", name: "Flow 开发组", slug: "flow-dev" },
    project_detail: {
      id: "proj-1",
      identifier: "FF",
      name: "Flow 前端",
      cover_image: "",
      description: null,
      emoji: null,
      icon_prop: null,
    },
    issue_detail: {
      id: "issue-7",
      sequence_id: 7,
      sort_order: false as any,
      name: "重构通知模块状态管理",
      description_html: "",
      priority: "low" as any,
      start_date: "",
      target_date: "",
      is_draft: false,
    },
    edited_at: undefined,
  },
];

// ---------------------------------------------------------------------------
// Issue Activities (for activity log — per RESEARCH.md)
// ---------------------------------------------------------------------------

export const MOCK_ISSUE_ACTIVITIES: TIssueActivity[] = [
  {
    id: "iact-1",
    workspace: "ws-1",
    project: "proj-1",
    issue: "issue-1",
    actor: "user-1",
    actor_detail: {
      id: "user-1",
      first_name: "张三",
      last_name: "",
      avatar_url: "",
      is_bot: false,
      display_name: "张三",
    },
    created_at: new Date(now - dayMs * 3).toISOString(),
    updated_at: new Date(now - dayMs * 3).toISOString(),
    created_by: "user-1",
    updated_by: "user-1",
    attachments: [],
    verb: "created",
    field: "name",
    old_value: undefined,
    new_value: undefined,
    old_identifier: undefined,
    new_identifier: undefined,
    comment: undefined,
    epoch: now - dayMs * 3,
    issue_comment: null,
    workspace_detail: { id: "ws-1", name: "Flow 开发组", slug: "flow-dev" },
    project_detail: {
      id: "proj-1",
      identifier: "FF",
      name: "Flow 前端",
      cover_image: "",
      description: null,
      emoji: null,
      icon_prop: null,
    },
    issue_detail: {
      id: "issue-1",
      sequence_id: 1,
      sort_order: false as any,
      name: "实现用户登录页面 UI",
      description_html: "",
      priority: "high" as any,
      start_date: "",
      target_date: "",
      is_draft: false,
    },
    source_data: { source: "web" as any, extra: {} },
  },
  {
    id: "iact-2",
    workspace: "ws-1",
    project: "proj-1",
    issue: "issue-1",
    actor: "user-2",
    actor_detail: {
      id: "user-2",
      first_name: "李四",
      last_name: "",
      avatar_url: "",
      is_bot: false,
      display_name: "李四",
    },
    created_at: new Date(now - dayMs * 2).toISOString(),
    updated_at: new Date(now - dayMs * 2).toISOString(),
    created_by: "user-2",
    updated_by: "user-2",
    attachments: [],
    verb: "updated",
    field: "state",
    old_value: "待办 (state-ff-1)",
    new_value: "进行中 (state-ff-3)",
    old_identifier: undefined,
    new_identifier: undefined,
    comment: undefined,
    epoch: now - dayMs * 2,
    issue_comment: null,
    workspace_detail: { id: "ws-1", name: "Flow 开发组", slug: "flow-dev" },
    project_detail: {
      id: "proj-1",
      identifier: "FF",
      name: "Flow 前端",
      cover_image: "",
      description: null,
      emoji: null,
      icon_prop: null,
    },
    issue_detail: {
      id: "issue-1",
      sequence_id: 1,
      sort_order: false as any,
      name: "实现用户登录页面 UI",
      description_html: "",
      priority: "high" as any,
      start_date: "",
      target_date: "",
      is_draft: false,
    },
    source_data: { source: "web" as any, extra: {} },
  },
  {
    id: "iact-3",
    workspace: "ws-1",
    project: "proj-1",
    issue: "issue-1",
    actor: "user-1",
    actor_detail: {
      id: "user-1",
      first_name: "张三",
      last_name: "",
      avatar_url: "",
      is_bot: false,
      display_name: "张三",
    },
    created_at: new Date(now - dayMs * 1).toISOString(),
    updated_at: new Date(now - dayMs * 1).toISOString(),
    created_by: "user-1",
    updated_by: "user-1",
    attachments: [],
    verb: "updated",
    field: "priority",
    old_value: "medium",
    new_value: "high",
    old_identifier: undefined,
    new_identifier: undefined,
    comment: undefined,
    epoch: now - dayMs * 1,
    issue_comment: null,
    workspace_detail: { id: "ws-1", name: "Flow 开发组", slug: "flow-dev" },
    project_detail: {
      id: "proj-1",
      identifier: "FF",
      name: "Flow 前端",
      cover_image: "",
      description: null,
      emoji: null,
      icon_prop: null,
    },
    issue_detail: {
      id: "issue-1",
      sequence_id: 1,
      sort_order: false as any,
      name: "实现用户登录页面 UI",
      description_html: "",
      priority: "high" as any,
      start_date: "",
      target_date: "",
      is_draft: false,
    },
    source_data: { source: "web" as any, extra: {} },
  },
  {
    id: "iact-4",
    workspace: "ws-1",
    project: "proj-1",
    issue: "issue-1",
    actor: "user-2",
    actor_detail: {
      id: "user-2",
      first_name: "李四",
      last_name: "",
      avatar_url: "",
      is_bot: false,
      display_name: "李四",
    },
    created_at: new Date(now - dayMs * 1).toISOString(),
    updated_at: new Date(now - dayMs * 1).toISOString(),
    created_by: "user-2",
    updated_by: "user-2",
    attachments: [],
    verb: "updated",
    field: "description",
    old_value: undefined,
    new_value: undefined,
    old_identifier: undefined,
    new_identifier: undefined,
    comment: "更新了 Issue 描述",
    epoch: now - dayMs * 1,
    issue_comment: null,
    workspace_detail: { id: "ws-1", name: "Flow 开发组", slug: "flow-dev" },
    project_detail: {
      id: "proj-1",
      identifier: "FF",
      name: "Flow 前端",
      cover_image: "",
      description: null,
      emoji: null,
      icon_prop: null,
    },
    issue_detail: {
      id: "issue-1",
      sequence_id: 1,
      sort_order: false as any,
      name: "实现用户登录页面 UI",
      description_html: "",
      priority: "high" as any,
      start_date: "",
      target_date: "",
      is_draft: false,
    },
    source_data: { source: "web" as any, extra: {} },
  },
  {
    id: "iact-5",
    workspace: "ws-1",
    project: "proj-1",
    issue: "issue-1",
    actor: "user-3",
    actor_detail: {
      id: "user-3",
      first_name: "王五",
      last_name: "",
      avatar_url: "",
      is_bot: false,
      display_name: "王五",
    },
    created_at: new Date(now).toISOString(),
    updated_at: new Date(now).toISOString(),
    created_by: "user-3",
    updated_by: "user-3",
    attachments: [],
    verb: "updated",
    field: "assignee",
    old_value: "",
    new_value: "user-3",
    old_identifier: undefined,
    new_identifier: undefined,
    comment: undefined,
    epoch: now,
    issue_comment: null,
    workspace_detail: { id: "ws-1", name: "Flow 开发组", slug: "flow-dev" },
    project_detail: {
      id: "proj-1",
      identifier: "FF",
      name: "Flow 前端",
      cover_image: "",
      description: null,
      emoji: null,
      icon_prop: null,
    },
    issue_detail: {
      id: "issue-1",
      sequence_id: 1,
      sort_order: false as any,
      name: "实现用户登录页面 UI",
      description_html: "",
      priority: "high" as any,
      start_date: "",
      target_date: "",
      is_draft: false,
    },
    source_data: { source: "web" as any, extra: {} },
  },
  {
    id: "iact-6",
    workspace: "ws-1",
    project: "proj-2",
    issue: "issue-8",
    actor: "user-1",
    actor_detail: {
      id: "user-1",
      first_name: "张三",
      last_name: "",
      avatar_url: "",
      is_bot: false,
      display_name: "张三",
    },
    created_at: new Date(now - dayMs * 15).toISOString(),
    updated_at: new Date(now - dayMs * 15).toISOString(),
    created_by: "user-1",
    updated_by: "user-1",
    attachments: [],
    verb: "created",
    field: "name",
    old_value: undefined,
    new_value: undefined,
    old_identifier: undefined,
    new_identifier: undefined,
    comment: undefined,
    epoch: now - dayMs * 15,
    issue_comment: null,
    workspace_detail: { id: "ws-1", name: "Flow 开发组", slug: "flow-dev" },
    project_detail: {
      id: "proj-2",
      identifier: "FA",
      name: "Flow API",
      cover_image: "",
      description: null,
      emoji: null,
      icon_prop: null,
    },
    issue_detail: {
      id: "issue-8",
      sequence_id: 1,
      sort_order: false as any,
      name: "设计 Issue 数据模型",
      description_html: "",
      priority: "urgent" as any,
      start_date: "",
      target_date: "",
      is_draft: false,
    },
    source_data: { source: "web" as any, extra: {} },
  },
  {
    id: "iact-7",
    workspace: "ws-1",
    project: "proj-2",
    issue: "issue-8",
    actor: "user-3",
    actor_detail: {
      id: "user-3",
      first_name: "王五",
      last_name: "",
      avatar_url: "",
      is_bot: false,
      display_name: "王五",
    },
    created_at: new Date(now - dayMs * 12).toISOString(),
    updated_at: new Date(now - dayMs * 12).toISOString(),
    created_by: "user-3",
    updated_by: "user-3",
    attachments: [],
    verb: "updated",
    field: "assignee",
    old_value: "",
    new_value: "user-3",
    old_identifier: undefined,
    new_identifier: undefined,
    comment: undefined,
    epoch: now - dayMs * 12,
    issue_comment: null,
    workspace_detail: { id: "ws-1", name: "Flow 开发组", slug: "flow-dev" },
    project_detail: {
      id: "proj-2",
      identifier: "FA",
      name: "Flow API",
      cover_image: "",
      description: null,
      emoji: null,
      icon_prop: null,
    },
    issue_detail: {
      id: "issue-8",
      sequence_id: 1,
      sort_order: false as any,
      name: "设计 Issue 数据模型",
      description_html: "",
      priority: "urgent" as any,
      start_date: "",
      target_date: "",
      is_draft: false,
    },
    source_data: { source: "web" as any, extra: {} },
  },
  {
    id: "iact-8",
    workspace: "ws-1",
    project: "proj-1",
    issue: "issue-5",
    actor: "user-1",
    actor_detail: {
      id: "user-1",
      first_name: "张三",
      last_name: "",
      avatar_url: "",
      is_bot: false,
      display_name: "张三",
    },
    created_at: new Date(now - dayMs * 10).toISOString(),
    updated_at: new Date(now - dayMs * 10).toISOString(),
    created_by: "user-1",
    updated_by: "user-1",
    attachments: [],
    verb: "created",
    field: "name",
    old_value: undefined,
    new_value: undefined,
    old_identifier: undefined,
    new_identifier: undefined,
    comment: undefined,
    epoch: now - dayMs * 10,
    issue_comment: null,
    workspace_detail: { id: "ws-1", name: "Flow 开发组", slug: "flow-dev" },
    project_detail: {
      id: "proj-1",
      identifier: "FF",
      name: "Flow 前端",
      cover_image: "",
      description: null,
      emoji: null,
      icon_prop: null,
    },
    issue_detail: {
      id: "issue-5",
      sequence_id: 5,
      sort_order: false as any,
      name: "添加暗色模式支持",
      description_html: "",
      priority: "high" as any,
      start_date: "",
      target_date: "",
      is_draft: false,
    },
    source_data: { source: "web" as any, extra: {} },
  },
];

// Dict form for useComments lookup
export const MOCK_COMMENTS: Record<string, TIssueComment[]> = MOCK_ISSUE_COMMENTS.reduce(
  (acc, c) => {
    const key = c.issue;
    if (!acc[key]) acc[key] = [];
    acc[key].push(c);
    return acc;
  },
  {} as Record<string, TIssueComment[]>,
);

export const _ws1Detail = { id: "ws-1", name: "Flow 开发组", slug: "flow-dev", logo_url: "", logo_props: {} };
export const _proj1Detail = { id: "proj-1", identifier: "FF", name: "Flow 前端", cover_image: "", description: null, emoji: null, icon_prop: null };
export const _user1Detail = { id: "user-1", first_name: "我", last_name: "", avatar: "", is_bot: false, display_name: "我" };
export const _user2Detail = { id: "user-2", first_name: "李四", last_name: "", avatar: "", is_bot: false, display_name: "李四" };
