// FLOW: Mock data layer for workspace/project UI development (per D-P15-12)
import type { IProject, IWorkspace, IWorkspaceMember } from "@plane/types";
import { EUserPermissions } from "@plane/types";
import type { TProjectBaseActivity } from "@plane/types";
import type { IState, IIssueLabel, TIssue, TIssueComment, TIssueActivity, TIssuePriorities } from "@plane/types";
import type {
  TIssueActivityWorkspaceDetail,
  TIssueActivityProjectDetail,
  TIssueActivityIssueDetail,
  TIssueActivityUserDetail,
  JSONContent,
} from "@plane/types";
import { EIssueCommentAccessSpecifier, EInboxIssueSource } from "@plane/types";

// ---------------------------------------------------------------------------
// Workspaces
// ---------------------------------------------------------------------------

export const MOCK_WORKSPACES: IWorkspace[] = [
  {
    id: "ws-1",
    name: "Flow 开发组",
    slug: "flow-dev",
    role: EUserPermissions.ADMIN,
    total_members: 5,
    total_projects: 3,
    owner: {
      id: "user-1",
      avatar_url: "",
      display_name: "Admin",
      first_name: "Admin",
      last_name: "",
      is_bot: false,
    } as IWorkspace["owner"],
    created_at: new Date("2026-01-15"),
    updated_at: new Date("2026-06-28"),
    url: "",
    logo_url: null,
    created_by: "user-1",
    updated_by: "user-1",
    organization_size: "10-50",
    timezone: "Asia/Shanghai",
  },
  {
    id: "ws-2",
    name: "个人空间",
    slug: "personal",
    role: EUserPermissions.MEMBER,
    total_members: 2,
    total_projects: 1,
    owner: {
      id: "user-2",
      avatar_url: "",
      display_name: "User",
      first_name: "User",
      last_name: "",
      is_bot: false,
    } as IWorkspace["owner"],
    created_at: new Date("2026-03-01"),
    updated_at: new Date("2026-06-20"),
    url: "",
    logo_url: null,
    created_by: "user-2",
    updated_by: "user-2",
    organization_size: "1-10",
    timezone: "Asia/Shanghai",
  },
];

// ---------------------------------------------------------------------------
// Projects
// ---------------------------------------------------------------------------

const makeLogoProps = (emojiCode: string) => ({
  in_use: "emoji" as const,
  emoji: { value: emojiCode },
});

export const MOCK_PROJECTS: IProject[] = [
  {
    id: "proj-1",
    name: "Flow 前端",
    identifier: "FF",
    logo_props: makeLogoProps("128640"),
    member_role: EUserPermissions.ADMIN,
    workspace: MOCK_WORKSPACES[0].id,
    sort_order: 1,
    archived_at: null,
    cycle_view: true,
    issue_views_view: true,
    module_view: true,
    page_view: true,
    inbox_view: true,
    created_at: new Date("2026-01-20"),
    updated_at: new Date("2026-06-28"),
    created_by: "user-1",
    updated_by: "user-1",
    description: "Flow 前端项目 — React + Vite + Tailwind CSS",
    is_favorite: true,
  },
  {
    id: "proj-2",
    name: "Flow API",
    identifier: "FA",
    logo_props: makeLogoProps("128187"),
    member_role: EUserPermissions.ADMIN,
    workspace: MOCK_WORKSPACES[0].id,
    sort_order: 2,
    archived_at: null,
    cycle_view: true,
    issue_views_view: true,
    module_view: true,
    page_view: true,
    inbox_view: true,
    created_at: new Date("2026-02-01"),
    updated_at: new Date("2026-06-27"),
    created_by: "user-1",
    updated_by: "user-1",
    description: "Flow API — .NET 10 Modular Monolith",
  },
  {
    id: "proj-3",
    name: "Flow 文档",
    identifier: "FD",
    logo_props: makeLogoProps("128214"),
    member_role: EUserPermissions.MEMBER,
    workspace: MOCK_WORKSPACES[0].id,
    sort_order: 3,
    archived_at: null,
    cycle_view: false,
    issue_views_view: false,
    module_view: false,
    page_view: true,
    inbox_view: false,
    created_at: new Date("2026-03-10"),
    updated_at: new Date("2026-06-25"),
    created_by: "user-1",
    updated_by: "user-2",
    description: "项目文档和 Wiki",
  },
  {
    id: "proj-4",
    name: "个人笔记",
    identifier: "PN",
    logo_props: makeLogoProps("128221"),
    member_role: EUserPermissions.MEMBER,
    workspace: MOCK_WORKSPACES[1].id,
    sort_order: 1,
    archived_at: null,
    cycle_view: false,
    issue_views_view: false,
    module_view: false,
    page_view: true,
    inbox_view: false,
    created_at: new Date("2026-03-05"),
    updated_at: new Date("2026-06-20"),
    created_by: "user-2",
    updated_by: "user-2",
    description: "个人笔记和待办事项",
  },
];

// ---------------------------------------------------------------------------
// Members
// ---------------------------------------------------------------------------

export const MOCK_MEMBERS: Record<string, IWorkspaceMember[]> = {
  "ws-1": [
    {
      id: "mem-1",
      member: {
        id: "user-1",
        avatar_url: "",
        display_name: "张三",
        first_name: "张三",
        last_name: "",
        is_bot: false,
      },
      role: EUserPermissions.ADMIN,
      email: "zhangsan@example.com",
    },
    {
      id: "mem-2",
      member: {
        id: "user-2",
        avatar_url: "",
        display_name: "李四",
        first_name: "李四",
        last_name: "",
        is_bot: false,
      },
      role: EUserPermissions.MEMBER,
      email: "lisi@example.com",
    },
    {
      id: "mem-3",
      member: {
        id: "user-3",
        avatar_url: "",
        display_name: "王五",
        first_name: "王五",
        last_name: "",
        is_bot: false,
      },
      role: EUserPermissions.MEMBER,
      email: "wangwu@example.com",
    },
    {
      id: "mem-4",
      member: {
        id: "user-4",
        avatar_url: "",
        display_name: "赵六",
        first_name: "赵六",
        last_name: "",
        is_bot: false,
      },
      role: EUserPermissions.GUEST,
      email: "zhaoliu@example.com",
    },
    {
      id: "mem-5",
      member: {
        id: "user-5",
        avatar_url: "",
        display_name: "陈七",
        first_name: "陈七",
        last_name: "",
        is_bot: false,
      },
      role: EUserPermissions.MEMBER,
      email: "chenqi@example.com",
    },
  ],
  "ws-2": [
    {
      id: "mem-6",
      member: {
        id: "user-2",
        avatar_url: "",
        display_name: "李四",
        first_name: "李四",
        last_name: "",
        is_bot: false,
      },
      role: EUserPermissions.ADMIN,
      email: "lisi@example.com",
    },
    {
      id: "mem-7",
      member: {
        id: "user-6",
        avatar_url: "",
        display_name: "周八",
        first_name: "周八",
        last_name: "",
        is_bot: false,
      },
      role: EUserPermissions.MEMBER,
      email: "zhouba@example.com",
    },
  ],
};

// ---------------------------------------------------------------------------
// Activities
// ---------------------------------------------------------------------------

const now = Date.now();
const dayMs = 86400 * 1000;

export const MOCK_ACTIVITIES: TProjectBaseActivity[] = [
  {
    id: "act-1",
    field: "name",
    epoch: now,
    verb: "created",
    comment: undefined,
    old_value: undefined,
    new_value: undefined,
    old_identifier: undefined,
    new_identifier: undefined,
    actor: "user-1",
    created_at: new Date(now).toISOString(),
    updated_at: new Date(now).toISOString(),
    workspace: "ws-1",
    project: "proj-1",
  },
  {
    id: "act-2",
    field: "state",
    epoch: now - dayMs * 1,
    verb: "updated",
    comment: undefined,
    old_value: "backlog",
    new_value: "in_progress",
    old_identifier: undefined,
    new_identifier: undefined,
    actor: "user-2",
    created_at: new Date(now - dayMs * 1).toISOString(),
    updated_at: new Date(now - dayMs * 1).toISOString(),
    workspace: "ws-1",
    project: "proj-1",
  },
  {
    id: "act-3",
    field: "assignee",
    epoch: now - dayMs * 2,
    verb: "updated",
    comment: undefined,
    old_value: "",
    new_value: "user-3",
    old_identifier: undefined,
    new_identifier: undefined,
    actor: "user-1",
    created_at: new Date(now - dayMs * 2).toISOString(),
    updated_at: new Date(now - dayMs * 2).toISOString(),
    workspace: "ws-1",
    project: "proj-2",
  },
  {
    id: "act-4",
    field: "description",
    epoch: now - dayMs * 3,
    verb: "created",
    comment: "添加了新的 API 文档",
    old_value: undefined,
    new_value: undefined,
    old_identifier: undefined,
    new_identifier: undefined,
    actor: "user-1",
    created_at: new Date(now - dayMs * 3).toISOString(),
    updated_at: new Date(now - dayMs * 3).toISOString(),
    workspace: "ws-1",
    project: "proj-2",
  },
  {
    id: "act-5",
    field: "name",
    epoch: now - dayMs * 5,
    verb: "created",
    comment: undefined,
    old_value: undefined,
    new_value: undefined,
    old_identifier: undefined,
    new_identifier: undefined,
    actor: "user-2",
    created_at: new Date(now - dayMs * 5).toISOString(),
    updated_at: new Date(now - dayMs * 5).toISOString(),
    workspace: "ws-2",
    project: "proj-4",
  },
  {
    id: "act-6",
    field: "priority",
    epoch: now - dayMs * 7,
    verb: "updated",
    comment: undefined,
    old_value: "low",
    new_value: "urgent",
    old_identifier: undefined,
    new_identifier: undefined,
    actor: "user-2",
    created_at: new Date(now - dayMs * 7).toISOString(),
    updated_at: new Date(now - dayMs * 7).toISOString(),
    workspace: "ws-2",
    project: "proj-4",
  },
  {
    id: "act-7",
    field: "state",
    epoch: now - dayMs * 10,
    verb: "updated",
    comment: undefined,
    old_value: "in_progress",
    new_value: "done",
    old_identifier: undefined,
    new_identifier: undefined,
    actor: "user-1",
    created_at: new Date(now - dayMs * 10).toISOString(),
    updated_at: new Date(now - dayMs * 10).toISOString(),
    workspace: "ws-1",
    project: "proj-1",
  },
  {
    id: "act-8",
    field: "name",
    epoch: now - dayMs * 14,
    verb: "created",
    comment: undefined,
    old_value: undefined,
    new_value: undefined,
    old_identifier: undefined,
    new_identifier: undefined,
    actor: "user-1",
    created_at: new Date(now - dayMs * 14).toISOString(),
    updated_at: new Date(now - dayMs * 14).toISOString(),
    workspace: "ws-1",
    project: "proj-3",
  },
];

// ---------------------------------------------------------------------------
// State detail helpers for comments and activities
// ---------------------------------------------------------------------------
export const _ws1Detail: TIssueActivityWorkspaceDetail = {
  name: "Flow 开发组",
  slug: "flow-dev",
  id: "ws-1",
};
export const _proj1Detail: TIssueActivityProjectDetail = {
  id: "proj-1",
  identifier: "FF",
  name: "Flow 前端",
  cover_image: "",
  description: "Flow 前端项目 --- React + Vite + Tailwind CSS",
  emoji: null,
  icon_prop: null,
};
export const _proj2Detail: TIssueActivityProjectDetail = {
  id: "proj-2",
  identifier: "FA",
  name: "Flow API",
  cover_image: "",
  description: "Flow API --- .NET 10 Modular Monolith",
  emoji: null,
  icon_prop: null,
};
export const _user1Detail: TIssueActivityUserDetail = {
  id: "user-1",
  first_name: "张三",
  last_name: "",
  avatar_url: "",
  is_bot: false,
  display_name: "张三",
};
const _user2Detail: TIssueActivityUserDetail = {
  id: "user-2",
  first_name: "李四",
  last_name: "",
  avatar_url: "",
  is_bot: false,
  display_name: "李四",
};
const _user3Detail: TIssueActivityUserDetail = {
  id: "user-3",
  first_name: "王五",
  last_name: "",
  avatar_url: "",
  is_bot: false,
  display_name: "王五",
};

// ---------------------------------------------------------------------------
// States
// ---------------------------------------------------------------------------

export const MOCK_STATES: IState[] = [
  // proj-1 (Flow 前端)
  {
    id: "state-ff-bklg",
    color: "#a3a3a3",
    default: true,
    description: "待处理",
    group: "backlog",
    name: "Backlog",
    project_id: "proj-1",
    sequence: 1,
    workspace_id: "ws-1",
    order: 1,
  },
  {
    id: "state-ff-unstarted",
    color: "#3b82f6",
    default: false,
    description: "未开始",
    group: "unstarted",
    name: "未开始",
    project_id: "proj-1",
    sequence: 2,
    workspace_id: "ws-1",
    order: 2,
  },
  {
    id: "state-ff-started",
    color: "#f59e0b",
    default: false,
    description: "进行中",
    group: "started",
    name: "进行中",
    project_id: "proj-1",
    sequence: 3,
    workspace_id: "ws-1",
    order: 3,
  },
  {
    id: "state-ff-completed",
    color: "#22c55e",
    default: false,
    description: "已完成",
    group: "completed",
    name: "已完成",
    project_id: "proj-1",
    sequence: 4,
    workspace_id: "ws-1",
    order: 4,
  },
  {
    id: "state-ff-cancelled",
    color: "#ef4444",
    default: false,
    description: "已取消",
    group: "cancelled",
    name: "已取消",
    project_id: "proj-1",
    sequence: 5,
    workspace_id: "ws-1",
    order: 5,
  },
  // proj-2 (Flow API)
  {
    id: "state-fa-bklg",
    color: "#a3a3a3",
    default: true,
    description: "待处理",
    group: "backlog",
    name: "Backlog",
    project_id: "proj-2",
    sequence: 6,
    workspace_id: "ws-1",
    order: 1,
  },
  {
    id: "state-fa-unstarted",
    color: "#3b82f6",
    default: false,
    description: "未开始",
    group: "unstarted",
    name: "未开始",
    project_id: "proj-2",
    sequence: 7,
    workspace_id: "ws-1",
    order: 2,
  },
  {
    id: "state-fa-started",
    color: "#f59e0b",
    default: false,
    description: "进行中",
    group: "started",
    name: "进行中",
    project_id: "proj-2",
    sequence: 8,
    workspace_id: "ws-1",
    order: 3,
  },
  {
    id: "state-fa-completed",
    color: "#22c55e",
    default: false,
    description: "已完成",
    group: "completed",
    name: "已完成",
    project_id: "proj-2",
    sequence: 9,
    workspace_id: "ws-1",
    order: 4,
  },
  {
    id: "state-fa-cancelled",
    color: "#ef4444",
    default: false,
    description: "已取消",
    group: "cancelled",
    name: "已取消",
    project_id: "proj-2",
    sequence: 10,
    workspace_id: "ws-1",
    order: 5,
  },
];

// ---------------------------------------------------------------------------
// Labels
// ---------------------------------------------------------------------------

export const MOCK_LABELS: IIssueLabel[] = [
  {
    id: "label-1",
    name: "前端",
    color: "#3B82F6",
    project_id: "proj-1",
    workspace_id: "ws-1",
    parent: null,
    sort_order: 1,
  },
  {
    id: "label-2",
    name: "后端",
    color: "#10B981",
    project_id: "proj-1",
    workspace_id: "ws-1",
    parent: null,
    sort_order: 2,
  },
  {
    id: "label-3",
    name: "Bug",
    color: "#EF4444",
    project_id: "proj-1",
    workspace_id: "ws-1",
    parent: null,
    sort_order: 3,
  },
  {
    id: "label-4",
    name: "API",
    color: "#8B5CF6",
    project_id: "proj-2",
    workspace_id: "ws-1",
    parent: null,
    sort_order: 4,
  },
  {
    id: "label-5",
    name: "数据库",
    color: "#F59E0B",
    project_id: "proj-2",
    workspace_id: "ws-1",
    parent: null,
    sort_order: 5,
  },
  {
    id: "label-6",
    name: "文档",
    color: "#6B7280",
    project_id: "proj-2",
    workspace_id: "ws-1",
    parent: null,
    sort_order: 6,
  },
];

// ---------------------------------------------------------------------------
// Issues
// ---------------------------------------------------------------------------

const _mkIssueDetail = (
  id: string,
  seq: number,
  name: string,
  priority: TIssuePriorities
): TIssueActivityIssueDetail => ({
  id,
  sequence_id: seq,
  sort_order: true as unknown as boolean,
  name,
  description_html: "",
  priority: priority as TIssuePriorities,
  start_date: "",
  target_date: "",
  is_draft: false,
});

export const MOCK_ISSUES: TIssue[] = [
  // ========================================================================
  // proj-1 (Flow 前端) — 12 issues
  // ========================================================================
  {
    id: "issue-ff-1",
    sequence_id: 1,
    name: "用户登录页面重构",
    project_id: "proj-1",
    state_id: "state-ff-started",
    priority: "high",
    assignee_ids: ["user-1", "user-2"],
    label_ids: ["label-1"],
    estimate_point: "8",
    sub_issues_count: 2,
    attachment_count: 1,
    link_count: 1,
    parent_id: null,
    cycle_id: null,
    module_ids: null,
    type_id: null,
    is_draft: false,
    sort_order: 15000,
    created_at: new Date(now - dayMs * 28).toISOString(),
    updated_at: new Date(now - dayMs * 1).toISOString(),
    start_date: new Date(now - dayMs * 14).toISOString(),
    target_date: new Date(now + dayMs * 7).toISOString(),
    completed_at: null,
    archived_at: null,
    created_by: "user-1",
    updated_by: "user-2",
    description_html: "<h2>概述</h2><p>重构用户登录页面，支持多因素认证和社交登录</p>",
  },
  {
    id: "issue-ff-2",
    sequence_id: 2,
    name: "导航栏响应式适配",
    project_id: "proj-1",
    state_id: "state-ff-started",
    priority: "medium",
    assignee_ids: ["user-2"],
    label_ids: ["label-1", "label-3"],
    estimate_point: "3",
    sub_issues_count: 1,
    attachment_count: 0,
    link_count: 0,
    parent_id: null,
    cycle_id: null,
    module_ids: null,
    type_id: null,
    is_draft: false,
    sort_order: 25000,
    created_at: new Date(now - dayMs * 25).toISOString(),
    updated_at: new Date(now - dayMs * 2).toISOString(),
    start_date: new Date(now - dayMs * 10).toISOString(),
    target_date: new Date(now + dayMs * 5).toISOString(),
    completed_at: null,
    archived_at: null,
    created_by: "user-2",
    updated_by: "user-2",
  },
  {
    id: "issue-ff-3",
    sequence_id: 3,
    name: "暗色模式主题系统",
    project_id: "proj-1",
    state_id: "state-ff-bklg",
    priority: "medium",
    assignee_ids: ["user-1"],
    label_ids: ["label-1"],
    estimate_point: "5",
    sub_issues_count: 0,
    attachment_count: 0,
    link_count: 0,
    parent_id: null,
    cycle_id: null,
    module_ids: null,
    type_id: null,
    is_draft: false,
    sort_order: 35000,
    created_at: new Date(now - dayMs * 22).toISOString(),
    updated_at: new Date(now - dayMs * 3).toISOString(),
    start_date: null,
    target_date: null,
    completed_at: null,
    archived_at: null,
    created_by: "user-1",
    updated_by: "user-1",
  },
  {
    id: "issue-ff-4",
    sequence_id: 4,
    name: "Dashboard 数据图表",
    project_id: "proj-1",
    state_id: "state-ff-unstarted",
    priority: "high",
    assignee_ids: ["user-1"],
    label_ids: ["label-1", "label-2"],
    estimate_point: null,
    sub_issues_count: 0,
    attachment_count: 1,
    link_count: 1,
    parent_id: null,
    cycle_id: null,
    module_ids: null,
    type_id: null,
    is_draft: false,
    sort_order: 45000,
    created_at: new Date(now - dayMs * 20).toISOString(),
    updated_at: new Date(now - dayMs * 4).toISOString(),
    start_date: new Date(now - dayMs * 5).toISOString(),
    target_date: new Date(now + dayMs * 10).toISOString(),
    completed_at: null,
    archived_at: null,
    created_by: "user-1",
    updated_by: "user-1",
  },
  {
    id: "issue-ff-5",
    sequence_id: 5,
    name: "搜索功能前端实现",
    project_id: "proj-1",
    state_id: "state-ff-unstarted",
    priority: "medium",
    assignee_ids: ["user-3"],
    label_ids: ["label-1"],
    estimate_point: "5",
    sub_issues_count: 2,
    attachment_count: 0,
    link_count: 0,
    parent_id: null,
    cycle_id: null,
    module_ids: null,
    type_id: null,
    is_draft: false,
    sort_order: 55000,
    created_at: new Date(now - dayMs * 18).toISOString(),
    updated_at: new Date(now - dayMs * 5).toISOString(),
    start_date: null,
    target_date: null,
    completed_at: null,
    archived_at: null,
    created_by: "user-3",
    updated_by: "user-1",
  },
  {
    id: "issue-ff-6",
    sequence_id: 6,
    name: "通知弹窗组件开发",
    project_id: "proj-1",
    state_id: "state-ff-started",
    priority: "low",
    assignee_ids: ["user-2"],
    label_ids: ["label-1"],
    estimate_point: "2",
    sub_issues_count: 1,
    attachment_count: 0,
    link_count: 0,
    parent_id: null,
    cycle_id: null,
    module_ids: null,
    type_id: null,
    is_draft: false,
    sort_order: 65000,
    created_at: new Date(now - dayMs * 16).toISOString(),
    updated_at: new Date(now - dayMs * 1).toISOString(),
    start_date: new Date(now - dayMs * 3).toISOString(),
    target_date: new Date(now + dayMs * 3).toISOString(),
    completed_at: null,
    archived_at: null,
    created_by: "user-2",
    updated_by: "user-2",
  },
  {
    id: "issue-ff-7",
    sequence_id: 7,
    name: "性能优化：组件懒加载",
    project_id: "proj-1",
    state_id: "state-ff-bklg",
    priority: "high",
    assignee_ids: ["user-1"],
    label_ids: ["label-1", "label-2"],
    estimate_point: "3",
    sub_issues_count: 0,
    attachment_count: 0,
    link_count: 0,
    parent_id: null,
    cycle_id: null,
    module_ids: null,
    type_id: null,
    is_draft: false,
    sort_order: 75000,
    created_at: new Date(now - dayMs * 14).toISOString(),
    updated_at: new Date(now - dayMs * 6).toISOString(),
    start_date: null,
    target_date: null,
    completed_at: null,
    archived_at: null,
    created_by: "user-1",
    updated_by: "user-1",
  },
  {
    id: "issue-ff-8",
    sequence_id: 8,
    name: "表单验证库集成",
    project_id: "proj-1",
    state_id: "state-ff-bklg",
    priority: "low",
    assignee_ids: ["user-3"],
    label_ids: ["label-2"],
    estimate_point: null,
    sub_issues_count: 0,
    attachment_count: 0,
    link_count: 0,
    parent_id: null,
    cycle_id: null,
    module_ids: null,
    type_id: null,
    is_draft: false,
    sort_order: 85000,
    created_at: new Date(now - dayMs * 12).toISOString(),
    updated_at: new Date(now - dayMs * 5).toISOString(),
    start_date: null,
    target_date: null,
    completed_at: null,
    archived_at: null,
    created_by: "user-3",
    updated_by: "user-3",
  },
  {
    id: "issue-ff-9",
    sequence_id: 9,
    name: "国际化 i18n 支持",
    project_id: "proj-1",
    state_id: "state-ff-unstarted",
    priority: "medium",
    assignee_ids: [],
    label_ids: ["label-1"],
    estimate_point: "8",
    sub_issues_count: 0,
    attachment_count: 0,
    link_count: 0,
    parent_id: null,
    cycle_id: null,
    module_ids: null,
    type_id: null,
    is_draft: false,
    sort_order: 95000,
    created_at: new Date(now - dayMs * 10).toISOString(),
    updated_at: new Date(now - dayMs * 4).toISOString(),
    start_date: null,
    target_date: null,
    completed_at: null,
    archived_at: null,
    created_by: "user-1",
    updated_by: "user-1",
  },
  {
    id: "issue-ff-10",
    sequence_id: 10,
    name: "单元测试框架配置",
    project_id: "proj-1",
    state_id: "state-ff-completed",
    priority: "none",
    assignee_ids: ["user-1"],
    label_ids: ["label-2"],
    estimate_point: "2",
    sub_issues_count: 0,
    attachment_count: 1,
    link_count: 0,
    parent_id: null,
    cycle_id: null,
    module_ids: null,
    type_id: null,
    is_draft: false,
    sort_order: 105000,
    created_at: new Date(now - dayMs * 8).toISOString(),
    updated_at: new Date(now - dayMs * 1).toISOString(),
    start_date: new Date(now - dayMs * 6).toISOString(),
    target_date: new Date(now - dayMs * 2).toISOString(),
    completed_at: new Date(now - dayMs * 2).toISOString(),
    archived_at: null,
    created_by: "user-1",
    updated_by: "user-1",
  },
  {
    id: "issue-ff-11",
    sequence_id: 11,
    name: "CI/CD 前端流水线",
    project_id: "proj-1",
    state_id: "state-ff-completed",
    priority: "low",
    assignee_ids: ["user-2"],
    label_ids: ["label-2"],
    estimate_point: "5",
    sub_issues_count: 0,
    attachment_count: 0,
    link_count: 1,
    parent_id: null,
    cycle_id: null,
    module_ids: null,
    type_id: null,
    is_draft: false,
    sort_order: 115000,
    created_at: new Date(now - dayMs * 6).toISOString(),
    updated_at: new Date(now - dayMs * 2).toISOString(),
    start_date: new Date(now - dayMs * 5).toISOString(),
    target_date: new Date(now - dayMs * 1).toISOString(),
    completed_at: new Date(now - dayMs * 1).toISOString(),
    archived_at: null,
    created_by: "user-2",
    updated_by: "user-2",
  },
  {
    id: "issue-ff-12",
    sequence_id: 12,
    name: "旧版页面样式迁移",
    project_id: "proj-1",
    state_id: "state-ff-cancelled",
    priority: "low",
    assignee_ids: [],
    label_ids: ["label-1", "label-3"],
    estimate_point: null,
    sub_issues_count: 0,
    attachment_count: 0,
    link_count: 0,
    parent_id: null,
    cycle_id: null,
    module_ids: null,
    type_id: null,
    is_draft: false,
    sort_order: 125000,
    created_at: new Date(now - dayMs * 4).toISOString(),
    updated_at: new Date(now - dayMs * 2).toISOString(),
    start_date: null,
    target_date: null,
    completed_at: null,
    archived_at: null,
    created_by: "user-2",
    updated_by: "user-1",
  },

  // ========================================================================
  // proj-2 (Flow API) — 8 issues
  // ========================================================================
  {
    id: "issue-fa-1",
    sequence_id: 1,
    name: "API 速率限制实现",
    project_id: "proj-2",
    state_id: "state-fa-started",
    priority: "urgent",
    assignee_ids: ["user-1"],
    label_ids: ["label-4"],
    estimate_point: "5",
    sub_issues_count: 2,
    attachment_count: 1,
    link_count: 1,
    parent_id: null,
    cycle_id: null,
    module_ids: null,
    type_id: null,
    is_draft: false,
    sort_order: 135000,
    created_at: new Date(now - dayMs * 29).toISOString(),
    updated_at: new Date(now - dayMs * 1).toISOString(),
    start_date: new Date(now - dayMs * 12).toISOString(),
    target_date: new Date(now + dayMs * 3).toISOString(),
    completed_at: null,
    archived_at: null,
    created_by: "user-1",
    updated_by: "user-1",
    description_html: "<h2>需求</h2><p>实现基于令牌桶算法的 API 速率限制中间件，支持按用户和按 IP 限流</p>",
  },
  {
    id: "issue-fa-2",
    sequence_id: 2,
    name: "数据库迁移脚本编写",
    project_id: "proj-2",
    state_id: "state-fa-started",
    priority: "high",
    assignee_ids: ["user-2"],
    label_ids: ["label-4", "label-5"],
    estimate_point: "8",
    sub_issues_count: 1,
    attachment_count: 0,
    link_count: 0,
    parent_id: null,
    cycle_id: null,
    module_ids: null,
    type_id: null,
    is_draft: false,
    sort_order: 145000,
    created_at: new Date(now - dayMs * 27).toISOString(),
    updated_at: new Date(now - dayMs * 3).toISOString(),
    start_date: new Date(now - dayMs * 10).toISOString(),
    target_date: new Date(now + dayMs * 5).toISOString(),
    completed_at: null,
    archived_at: null,
    created_by: "user-2",
    updated_by: "user-2",
  },
  {
    id: "issue-fa-3",
    sequence_id: 3,
    name: "用户权限中间件重构",
    project_id: "proj-2",
    state_id: "state-fa-bklg",
    priority: "high",
    assignee_ids: ["user-1"],
    label_ids: ["label-4"],
    estimate_point: "3",
    sub_issues_count: 0,
    attachment_count: 0,
    link_count: 0,
    parent_id: null,
    cycle_id: null,
    module_ids: null,
    type_id: null,
    is_draft: false,
    sort_order: 155000,
    created_at: new Date(now - dayMs * 24).toISOString(),
    updated_at: new Date(now - dayMs * 6).toISOString(),
    start_date: null,
    target_date: null,
    completed_at: null,
    archived_at: null,
    created_by: "user-1",
    updated_by: "user-1",
  },
  {
    id: "issue-fa-4",
    sequence_id: 4,
    name: "Swagger API 文档自动生成",
    project_id: "proj-2",
    state_id: "state-fa-unstarted",
    priority: "medium",
    assignee_ids: ["user-3"],
    label_ids: ["label-6"],
    estimate_point: null,
    sub_issues_count: 0,
    attachment_count: 1,
    link_count: 0,
    parent_id: null,
    cycle_id: null,
    module_ids: null,
    type_id: null,
    is_draft: false,
    sort_order: 165000,
    created_at: new Date(now - dayMs * 21).toISOString(),
    updated_at: new Date(now - dayMs * 5).toISOString(),
    start_date: null,
    target_date: null,
    completed_at: null,
    archived_at: null,
    created_by: "user-3",
    updated_by: "user-1",
  },
  {
    id: "issue-fa-5",
    sequence_id: 5,
    name: "Redis 缓存层集成",
    project_id: "proj-2",
    state_id: "state-fa-unstarted",
    priority: "medium",
    assignee_ids: ["user-1"],
    label_ids: ["label-4", "label-5"],
    estimate_point: "5",
    sub_issues_count: 0,
    attachment_count: 0,
    link_count: 0,
    parent_id: null,
    cycle_id: null,
    module_ids: null,
    type_id: null,
    is_draft: false,
    sort_order: 175000,
    created_at: new Date(now - dayMs * 19).toISOString(),
    updated_at: new Date(now - dayMs * 4).toISOString(),
    start_date: null,
    target_date: null,
    completed_at: null,
    archived_at: null,
    created_by: "user-1",
    updated_by: "user-1",
  },
  {
    id: "issue-fa-6",
    sequence_id: 6,
    name: "Webhook 事件通知引擎",
    project_id: "proj-2",
    state_id: "state-fa-started",
    priority: "high",
    assignee_ids: ["user-2"],
    label_ids: ["label-4"],
    estimate_point: "13",
    sub_issues_count: 3,
    attachment_count: 2,
    link_count: 1,
    parent_id: null,
    cycle_id: null,
    module_ids: null,
    type_id: null,
    is_draft: false,
    sort_order: 185000,
    created_at: new Date(now - dayMs * 17).toISOString(),
    updated_at: new Date(now - dayMs * 1).toISOString(),
    start_date: new Date(now - dayMs * 7).toISOString(),
    target_date: new Date(now + dayMs * 14).toISOString(),
    completed_at: null,
    archived_at: null,
    created_by: "user-2",
    updated_by: "user-2",
    description_html:
      "<h2>设计</h2><p>基于事件驱动的 Webhook 引擎，支持自定义事件类型和重试策略</p><p>使用 Hangfire 后台任务队列处理事件分发</p>",
  },
  {
    id: "issue-fa-7",
    sequence_id: 7,
    name: "OpenTelemetry 链路追踪",
    project_id: "proj-2",
    state_id: "state-fa-completed",
    priority: "medium",
    assignee_ids: ["user-1"],
    label_ids: ["label-4", "label-6"],
    estimate_point: "5",
    sub_issues_count: 0,
    attachment_count: 0,
    link_count: 0,
    parent_id: null,
    cycle_id: null,
    module_ids: null,
    type_id: null,
    is_draft: false,
    sort_order: 195000,
    created_at: new Date(now - dayMs * 15).toISOString(),
    updated_at: new Date(now - dayMs * 3).toISOString(),
    start_date: new Date(now - dayMs * 12).toISOString(),
    target_date: new Date(now - dayMs * 4).toISOString(),
    completed_at: new Date(now - dayMs * 4).toISOString(),
    archived_at: null,
    created_by: "user-1",
    updated_by: "user-1",
    description_html: "<h2>成果</h2><p>集成 OpenTelemetry SDK，实现 .NET 应用的分布式追踪、指标收集和日志导出</p>",
  },
  {
    id: "issue-fa-8",
    sequence_id: 8,
    name: "Docker Compose 开发环境",
    project_id: "proj-2",
    state_id: "state-fa-cancelled",
    priority: "none",
    assignee_ids: ["user-2"],
    label_ids: ["label-5"],
    estimate_point: null,
    sub_issues_count: 0,
    attachment_count: 0,
    link_count: 0,
    parent_id: null,
    cycle_id: null,
    module_ids: null,
    type_id: null,
    is_draft: false,
    sort_order: 205000,
    created_at: new Date(now - dayMs * 13).toISOString(),
    updated_at: new Date(now - dayMs * 7).toISOString(),
    start_date: null,
    target_date: null,
    completed_at: null,
    archived_at: null,
    created_by: "user-2",
    updated_by: "user-1",
  },
];

// ---------------------------------------------------------------------------
// Comments
// ---------------------------------------------------------------------------

const _mkComment = (
  id: string,
  issueId: string,
  issueSeq: number,
  issueName: string,
  actor: string,
  actorDetail: TIssueActivityUserDetail,
  commentHtml: string,
  commentStripped: string,
  projectDetail: TIssueActivityProjectDetail
): TIssueComment => ({
  id,
  workspace: "ws-1",
  workspace_detail: _ws1Detail,
  project: projectDetail.id,
  project_detail: projectDetail,
  issue: issueId,
  issue_detail: {
    id: issueId,
    sequence_id: issueSeq,
    sort_order: true as unknown as boolean,
    name: issueName,
    description_html: "",
    priority: "none" as TIssuePriorities,
    start_date: "",
    target_date: "",
    is_draft: false,
  },
  actor,
  actor_detail: actorDetail,
  created_at: new Date(now - dayMs * Math.floor(Math.random() * 7)).toISOString(),
  updated_at: new Date(now - dayMs * Math.floor(Math.random() * 7)).toISOString(),
  created_by: actor,
  updated_by: actor,
  attachments: [],
  comment_reactions: [],
  comment_stripped: commentStripped,
  comment_html: commentHtml,
  comment_json: {
    type: "doc",
    content: [{ type: "paragraph", content: [{ type: "text", text: commentStripped }] }],
  } as JSONContent,
  external_id: undefined,
  external_source: undefined,
  access: EIssueCommentAccessSpecifier.INTERNAL,
});

export const MOCK_COMMENTS: Record<string, TIssueComment[]> = {
  "issue-ff-1": [
    _mkComment(
      "cmt-ff1-1",
      "issue-ff-1",
      1,
      "用户登录页面重构",
      "user-1",
      _user1Detail,
      "<p>初步设计已完成，需要 review</p>",
      "初步设计已完成，需要 review",
      _proj1Detail
    ),
    _mkComment(
      "cmt-ff1-2",
      "issue-ff-1",
      1,
      "用户登录页面重构",
      "user-2",
      _user2Detail,
      "<p>收到，今天下午 Review</p>",
      "收到，今天下午 Review",
      _proj1Detail
    ),
    _mkComment(
      "cmt-ff1-3",
      "issue-ff-1",
      1,
      "用户登录页面重构",
      "user-1",
      _user1Detail,
      "<p>已根据反馈修改了布局细节</p>",
      "已根据反馈修改了布局细节",
      _proj1Detail
    ),
  ],
  "issue-ff-4": [
    _mkComment(
      "cmt-ff4-1",
      "issue-ff-4",
      4,
      "Dashboard 数据图表",
      "user-1",
      _user1Detail,
      "<p>需要和后端确认 API 返回格式</p>",
      "需要和后端确认 API 返回格式",
      _proj1Detail
    ),
    _mkComment(
      "cmt-ff4-2",
      "issue-ff-4",
      4,
      "Dashboard 数据图表",
      "user-1",
      _user1Detail,
      "<p>已确认使用 ECharts 作为图表库</p>",
      "已确认使用 ECharts 作为图表库",
      _proj1Detail
    ),
  ],
  "issue-ff-6": [
    _mkComment(
      "cmt-ff6-1",
      "issue-ff-6",
      6,
      "通知弹窗组件开发",
      "user-2",
      _user2Detail,
      "<p>参考了 shadcn 的 Sonner 实现</p>",
      "参考了 shadcn 的 Sonner 实现",
      _proj1Detail
    ),
  ],
  "issue-ff-10": [
    _mkComment(
      "cmt-ff10-1",
      "issue-ff-10",
      10,
      "单元测试框架配置",
      "user-1",
      _user1Detail,
      "<p>Vitest 配置完成，覆盖率阈值设为 80%</p>",
      "Vitest 配置完成，覆盖率阈值设为 80%",
      _proj1Detail
    ),
    _mkComment(
      "cmt-ff10-2",
      "issue-ff-10",
      10,
      "单元测试框架配置",
      "user-2",
      _user2Detail,
      "<p>不错，可以开始写测试了</p>",
      "不错，可以开始写测试了",
      _proj1Detail
    ),
  ],
  "issue-fa-1": [
    _mkComment(
      "cmt-fa1-1",
      "issue-fa-1",
      1,
      "API 速率限制实现",
      "user-1",
      _user1Detail,
      "<p>选用令牌桶算法，使用 Redis 存储计数器</p>",
      "选用令牌桶算法，使用 Redis 存储计数器",
      _proj2Detail
    ),
    _mkComment(
      "cmt-fa1-2",
      "issue-fa-1",
      1,
      "API 速率限制实现",
      "user-2",
      _user2Detail,
      "<p>需要考虑分布式场景下的原子操作</p>",
      "需要考虑分布式场景下的原子操作",
      _proj2Detail
    ),
    _mkComment(
      "cmt-fa1-3",
      "issue-fa-1",
      1,
      "API 速率限制实现",
      "user-1",
      _user1Detail,
      "<p>已使用 Lua 脚本保证原子性</p>",
      "已使用 Lua 脚本保证原子性",
      _proj2Detail
    ),
    _mkComment(
      "cmt-fa1-4",
      "issue-fa-1",
      1,
      "API 速率限制实现",
      "user-2",
      _user2Detail,
      "<p>LGTM, 可以合并了</p>",
      "LGTM, 可以合并了",
      _proj2Detail
    ),
  ],
  "issue-fa-6": [
    _mkComment(
      "cmt-fa6-1",
      "issue-fa-6",
      6,
      "Webhook 事件通知引擎",
      "user-2",
      _user2Detail,
      "<p>参考了 GitHub Webhooks 的接口设计</p>",
      "参考了 GitHub Webhooks 的接口设计",
      _proj2Detail
    ),
    _mkComment(
      "cmt-fa6-2",
      "issue-fa-6",
      6,
      "Webhook 事件通知引擎",
      "user-1",
      _user1Detail,
      "<p>重试策略如何设计？指数退避？</p>",
      "重试策略如何设计？指数退避？",
      _proj2Detail
    ),
    _mkComment(
      "cmt-fa6-3",
      "issue-fa-6",
      6,
      "Webhook 事件通知引擎",
      "user-2",
      _user2Detail,
      "<p>是的，最多重试 5 次，退避因子 2</p>",
      "是的，最多重试 5 次，退避因子 2",
      _proj2Detail
    ),
  ],
  "issue-fa-7": [
    _mkComment(
      "cmt-fa7-1",
      "issue-fa-7",
      7,
      "OpenTelemetry 链路追踪",
      "user-1",
      _user1Detail,
      "<p>已完成 Jaeger 和 Prometheus 的集成测试</p>",
      "已完成 Jaeger 和 Prometheus 的集成测试",
      _proj2Detail
    ),
  ],
};

// ---------------------------------------------------------------------------
// Issue Activities
// ---------------------------------------------------------------------------

const _mkActivity = (
  id: string,
  issueId: string,
  issueSeq: number,
  issueName: string,
  field: string | undefined,
  verb: string,
  oldVal: string | undefined,
  newVal: string | undefined,
  actor: string,
  actorDetail: TIssueActivityUserDetail,
  projectDetail: TIssueActivityProjectDetail,
  daysAgo: number
): TIssueActivity => ({
  id,
  workspace: "ws-1",
  workspace_detail: _ws1Detail,
  project: projectDetail.id,
  project_detail: projectDetail,
  issue: issueId,
  issue_detail: {
    id: issueId,
    sequence_id: issueSeq,
    sort_order: true as unknown as boolean,
    name: issueName,
    description_html: "",
    priority: "none" as TIssuePriorities,
    start_date: "",
    target_date: "",
    is_draft: false,
  },
  actor,
  actor_detail: actorDetail,
  created_at: new Date(now - dayMs * daysAgo).toISOString(),
  updated_at: new Date(now - dayMs * daysAgo).toISOString(),
  created_by: actor,
  updated_by: actor,
  attachments: [],
  verb,
  field,
  old_value: oldVal ?? undefined,
  new_value: newVal ?? undefined,
  comment: undefined,
  old_identifier: undefined,
  new_identifier: undefined,
  epoch: now - dayMs * daysAgo,
  issue_comment: null,
  source_data: {
    source: EInboxIssueSource.IN_APP,
    extra: {},
  },
});

export const MOCK_ISSUE_ACTIVITIES: TIssueActivity[] = [
  _mkActivity(
    "iact-ff1-1",
    "issue-ff-1",
    1,
    "用户登录页面重构",
    "name",
    "created",
    undefined,
    undefined,
    "user-1",
    _user1Detail,
    _proj1Detail,
    28
  ),
  _mkActivity(
    "iact-ff1-2",
    "issue-ff-1",
    1,
    "用户登录页面重构",
    "state",
    "updated",
    undefined,
    "started",
    "user-2",
    _user2Detail,
    _proj1Detail,
    14
  ),
  _mkActivity(
    "iact-ff1-3",
    "issue-ff-1",
    1,
    "用户登录页面重构",
    "priority",
    "updated",
    "medium",
    "high",
    "user-1",
    _user1Detail,
    _proj1Detail,
    7
  ),
  _mkActivity(
    "iact-ff4-1",
    "issue-ff-4",
    4,
    "Dashboard 数据图表",
    "name",
    "created",
    undefined,
    undefined,
    "user-1",
    _user1Detail,
    _proj1Detail,
    20
  ),
  _mkActivity(
    "iact-ff6-1",
    "issue-ff-6",
    6,
    "通知弹窗组件开发",
    "name",
    "created",
    undefined,
    undefined,
    "user-2",
    _user2Detail,
    _proj1Detail,
    16
  ),
  _mkActivity(
    "iact-ff10-1",
    "issue-ff-10",
    10,
    "单元测试框架配置",
    "name",
    "created",
    undefined,
    undefined,
    "user-1",
    _user1Detail,
    _proj1Detail,
    8
  ),
  _mkActivity(
    "iact-ff10-2",
    "issue-ff-10",
    10,
    "单元测试框架配置",
    "state",
    "updated",
    "started",
    "completed",
    "user-1",
    _user1Detail,
    _proj1Detail,
    2
  ),
  _mkActivity(
    "iact-fa1-1",
    "issue-fa-1",
    1,
    "API 速率限制实现",
    "name",
    "created",
    undefined,
    undefined,
    "user-1",
    _user1Detail,
    _proj2Detail,
    29
  ),
  _mkActivity(
    "iact-fa1-2",
    "issue-fa-1",
    1,
    "API 速率限制实现",
    "assignee",
    "updated",
    "",
    "user-1",
    "user-1",
    _user1Detail,
    _proj2Detail,
    15
  ),
  _mkActivity(
    "iact-fa2-1",
    "issue-fa-2",
    2,
    "数据库迁移脚本编写",
    "name",
    "created",
    undefined,
    undefined,
    "user-2",
    _user2Detail,
    _proj2Detail,
    27
  ),
  _mkActivity(
    "iact-fa6-1",
    "issue-fa-6",
    6,
    "Webhook 事件通知引擎",
    "name",
    "created",
    undefined,
    undefined,
    "user-2",
    _user2Detail,
    _proj2Detail,
    17
  ),
  _mkActivity(
    "iact-fa6-2",
    "issue-fa-6",
    6,
    "Webhook 事件通知引擎",
    "state",
    "updated",
    "backlog",
    "started",
    "user-2",
    _user2Detail,
    _proj2Detail,
    7
  ),
  _mkActivity(
    "iact-fa7-1",
    "issue-fa-7",
    7,
    "OpenTelemetry 链路追踪",
    "name",
    "created",
    undefined,
    undefined,
    "user-1",
    _user1Detail,
    _proj2Detail,
    15
  ),
  _mkActivity(
    "iact-fa8-1",
    "issue-fa-8",
    8,
    "Docker Compose 开发环境",
    "name",
    "created",
    undefined,
    undefined,
    "user-2",
    _user2Detail,
    _proj2Detail,
    13
  ),
  _mkActivity(
    "iact-fa8-2",
    "issue-fa-8",
    8,
    "Docker Compose 开发环境",
    "state",
    "updated",
    "started",
    "cancelled",
    "user-1",
    _user1Detail,
    _proj2Detail,
    7
  ),
];
