// FLOW: Mock data layer for workspace/project UI development (per D-P15-12)
import type {
  IProject,
  IState,
  IWorkspace,
  IWorkspaceMember,
  IIssueLabel,
  TIssue,
  TIssueActivity,
  TIssueComment,
  ICycle,
  IModule,
  TPage,
  TNotification,
  TUnreadNotificationsCount,
} from "@plane/types";
import { EUserPermissions, EPageAccess } from "@plane/types";
import type { TProjectBaseActivity } from "@plane/types";

// ---------------------------------------------------------------------------
// Workspaces
// ---------------------------------------------------------------------------

export const MOCK_WORKSPACES: IWorkspace[] = [
  {
    id: "ws-1",
    name: "Flow 开发组",
    slug: "flow-dev",
    role: EUserPermissions.ADMIN,
    total_members: 5,
    total_projects: 3,
    owner: {
      id: "user-1",
      avatar_url: "",
      display_name: "Admin",
      first_name: "Admin",
      last_name: "",
      is_bot: false,
    } as IWorkspace["owner"],
    created_at: new Date("2026-01-15"),
    updated_at: new Date("2026-06-28"),
    url: "",
    logo_url: null,
    created_by: "user-1",
    updated_by: "user-1",
    organization_size: "10-50",
    timezone: "Asia/Shanghai",
  },
  {
    id: "ws-2",
    name: "个人空间",
    slug: "personal",
    role: EUserPermissions.MEMBER,
    total_members: 2,
    total_projects: 1,
    owner: {
      id: "user-2",
      avatar_url: "",
      display_name: "User",
      first_name: "User",
      last_name: "",
      is_bot: false,
    } as IWorkspace["owner"],
    created_at: new Date("2026-03-01"),
    updated_at: new Date("2026-06-20"),
    url: "",
    logo_url: null,
    created_by: "user-2",
    updated_by: "user-2",
    organization_size: "1-10",
    timezone: "Asia/Shanghai",
  },
];

// ---------------------------------------------------------------------------
// Projects
// ---------------------------------------------------------------------------

const makeLogoProps = (emojiCode: string) => ({
  in_use: "emoji" as const,
  emoji: { value: emojiCode },
});

export const MOCK_PROJECTS: IProject[] = [
  {
    id: "proj-1",
    name: "Flow 前端",
    identifier: "FF",
    logo_props: makeLogoProps("128640"),
    member_role: EUserPermissions.ADMIN,
    workspace: MOCK_WORKSPACES[0].id,
    sort_order: 1,
    archived_at: null,
    cycle_view: true,
    issue_views_view: true,
    module_view: true,
    page_view: true,
    inbox_view: true,
    created_at: new Date("2026-01-20"),
    updated_at: new Date("2026-06-28"),
    created_by: "user-1",
    updated_by: "user-1",
    description: "Flow 前端项目 — React + Vite + Tailwind CSS",
    is_favorite: true,
  },
  {
    id: "proj-2",
    name: "Flow API",
    identifier: "FA",
    logo_props: makeLogoProps("128187"),
    member_role: EUserPermissions.ADMIN,
    workspace: MOCK_WORKSPACES[0].id,
    sort_order: 2,
    archived_at: null,
    cycle_view: true,
    issue_views_view: true,
    module_view: true,
    page_view: true,
    inbox_view: true,
    created_at: new Date("2026-02-01"),
    updated_at: new Date("2026-06-27"),
    created_by: "user-1",
    updated_by: "user-1",
    description: "Flow API — .NET 10 Modular Monolith",
  },
  {
    id: "proj-3",
    name: "Flow 文档",
    identifier: "FD",
    logo_props: makeLogoProps("128214"),
    member_role: EUserPermissions.MEMBER,
    workspace: MOCK_WORKSPACES[0].id,
    sort_order: 3,
    archived_at: null,
    cycle_view: false,
    issue_views_view: false,
    module_view: false,
    page_view: true,
    inbox_view: false,
    created_at: new Date("2026-03-10"),
    updated_at: new Date("2026-06-25"),
    created_by: "user-1",
    updated_by: "user-2",
    description: "项目文档和 Wiki",
  },
  {
    id: "proj-4",
    name: "个人笔记",
    identifier: "PN",
    logo_props: makeLogoProps("128221"),
    member_role: EUserPermissions.MEMBER,
    workspace: MOCK_WORKSPACES[1].id,
    sort_order: 1,
    archived_at: null,
    cycle_view: false,
    issue_views_view: false,
    module_view: false,
    page_view: true,
    inbox_view: false,
    created_at: new Date("2026-03-05"),
    updated_at: new Date("2026-06-20"),
    created_by: "user-2",
    updated_by: "user-2",
    description: "个人笔记和待办事项",
  },
];

// ---------------------------------------------------------------------------
// Members
// ---------------------------------------------------------------------------

export const MOCK_MEMBERS: Record<string, IWorkspaceMember[]> = {
  "ws-1": [
    {
      id: "mem-1",
      member: {
        id: "user-1",
        avatar_url: "",
        display_name: "张三",
        first_name: "张三",
        last_name: "",
        is_bot: false,
      },
      role: EUserPermissions.ADMIN,
      email: "zhangsan@example.com",
    },
    {
      id: "mem-2",
      member: {
        id: "user-2",
        avatar_url: "",
        display_name: "李四",
        first_name: "李四",
        last_name: "",
        is_bot: false,
      },
      role: EUserPermissions.MEMBER,
      email: "lisi@example.com",
    },
    {
      id: "mem-3",
      member: {
        id: "user-3",
        avatar_url: "",
        display_name: "王五",
        first_name: "王五",
        last_name: "",
        is_bot: false,
      },
      role: EUserPermissions.MEMBER,
      email: "wangwu@example.com",
    },
    {
      id: "mem-4",
      member: {
        id: "user-4",
        avatar_url: "",
        display_name: "赵六",
        first_name: "赵六",
        last_name: "",
        is_bot: false,
      },
      role: EUserPermissions.GUEST,
      email: "zhaoliu@example.com",
    },
    {
      id: "mem-5",
      member: {
        id: "user-5",
        avatar_url: "",
        display_name: "陈七",
        first_name: "陈七",
        last_name: "",
        is_bot: false,
      },
      role: EUserPermissions.MEMBER,
      email: "chenqi@example.com",
    },
  ],
  "ws-2": [
    {
      id: "mem-6",
      member: {
        id: "user-2",
        avatar_url: "",
        display_name: "李四",
        first_name: "李四",
        last_name: "",
        is_bot: false,
      },
      role: EUserPermissions.ADMIN,
      email: "lisi@example.com",
    },
    {
      id: "mem-7",
      member: {
        id: "user-6",
        avatar_url: "",
        display_name: "周八",
        first_name: "周八",
        last_name: "",
        is_bot: false,
      },
      role: EUserPermissions.MEMBER,
      email: "zhouba@example.com",
    },
  ],
};

// ---------------------------------------------------------------------------
// Activities
// ---------------------------------------------------------------------------

const now = Date.now();
const dayMs = 86400 * 1000;

export const MOCK_ACTIVITIES: TProjectBaseActivity[] = [
  {
    id: "act-1",
    field: "name",
    epoch: now,
    verb: "created",
    comment: undefined,
    old_value: undefined,
    new_value: undefined,
    old_identifier: undefined,
    new_identifier: undefined,
    actor: "user-1",
    created_at: new Date(now).toISOString(),
    updated_at: new Date(now).toISOString(),
    workspace: "ws-1",
    project: "proj-1",
  },
  {
    id: "act-2",
    field: "state",
    epoch: now - dayMs * 1,
    verb: "updated",
    comment: undefined,
    old_value: "backlog",
    new_value: "in_progress",
    old_identifier: undefined,
    new_identifier: undefined,
    actor: "user-2",
    created_at: new Date(now - dayMs * 1).toISOString(),
    updated_at: new Date(now - dayMs * 1).toISOString(),
    workspace: "ws-1",
    project: "proj-1",
  },
  {
    id: "act-3",
    field: "assignee",
    epoch: now - dayMs * 2,
    verb: "updated",
    comment: undefined,
    old_value: "",
    new_value: "user-3",
    old_identifier: undefined,
    new_identifier: undefined,
    actor: "user-1",
    created_at: new Date(now - dayMs * 2).toISOString(),
    updated_at: new Date(now - dayMs * 2).toISOString(),
    workspace: "ws-1",
    project: "proj-2",
  },
  {
    id: "act-4",
    field: "description",
    epoch: now - dayMs * 3,
    verb: "created",
    comment: "添加了新的 API 文档",
    old_value: undefined,
    new_value: undefined,
    old_identifier: undefined,
    new_identifier: undefined,
    actor: "user-1",
    created_at: new Date(now - dayMs * 3).toISOString(),
    updated_at: new Date(now - dayMs * 3).toISOString(),
    workspace: "ws-1",
    project: "proj-2",
  },
  {
    id: "act-5",
    field: "name",
    epoch: now - dayMs * 5,
    verb: "created",
    comment: undefined,
    old_value: undefined,
    new_value: undefined,
    old_identifier: undefined,
    new_identifier: undefined,
    actor: "user-2",
    created_at: new Date(now - dayMs * 5).toISOString(),
    updated_at: new Date(now - dayMs * 5).toISOString(),
    workspace: "ws-2",
    project: "proj-4",
  },
  {
    id: "act-6",
    field: "priority",
    epoch: now - dayMs * 7,
    verb: "updated",
    comment: undefined,
    old_value: "low",
    new_value: "urgent",
    old_identifier: undefined,
    new_identifier: undefined,
    actor: "user-2",
    created_at: new Date(now - dayMs * 7).toISOString(),
    updated_at: new Date(now - dayMs * 7).toISOString(),
    workspace: "ws-2",
    project: "proj-4",
  },
  {
    id: "act-7",
    field: "state",
    epoch: now - dayMs * 10,
    verb: "updated",
    comment: undefined,
    old_value: "in_progress",
    new_value: "done",
    old_identifier: undefined,
    new_identifier: undefined,
    actor: "user-1",
    created_at: new Date(now - dayMs * 10).toISOString(),
    updated_at: new Date(now - dayMs * 10).toISOString(),
    workspace: "ws-1",
    project: "proj-1",
  },
  {
    id: "act-8",
    field: "name",
    epoch: now - dayMs * 14,
    verb: "created",
    comment: undefined,
    old_value: undefined,
    new_value: undefined,
    old_identifier: undefined,
    new_identifier: undefined,
    actor: "user-1",
    created_at: new Date(now - dayMs * 14).toISOString(),
    updated_at: new Date(now - dayMs * 14).toISOString(),
    workspace: "ws-1",
    project: "proj-3",
  },
];

// ---------------------------------------------------------------------------
// States (per D-P16-03: extend with project states)
// ---------------------------------------------------------------------------

export const MOCK_STATES: IState[] = [
  {
    id: "state-ff-1",
    color: "#9CA3AF",
    default: true,
    description: "",
    group: "backlog",
    name: "待办",
    project_id: "proj-1",
    sequence: 1,
    workspace_id: "ws-1",
    order: 1,
  },
  {
    id: "state-ff-2",
    color: "#6B7280",
    default: false,
    description: "",
    group: "unstarted",
    name: "未开始",
    project_id: "proj-1",
    sequence: 2,
    workspace_id: "ws-1",
    order: 2,
  },
  {
    id: "state-ff-3",
    color: "#F59E0B",
    default: false,
    description: "",
    group: "started",
    name: "进行中",
    project_id: "proj-1",
    sequence: 3,
    workspace_id: "ws-1",
    order: 3,
  },
  {
    id: "state-ff-4",
    color: "#10B981",
    default: false,
    description: "",
    group: "completed",
    name: "已完成",
    project_id: "proj-1",
    sequence: 4,
    workspace_id: "ws-1",
    order: 4,
  },
  {
    id: "state-ff-5",
    color: "#EF4444",
    default: false,
    description: "",
    group: "cancelled",
    name: "已取消",
    project_id: "proj-1",
    sequence: 5,
    workspace_id: "ws-1",
    order: 5,
  },
  {
    id: "state-fa-1",
    color: "#9CA3AF",
    default: true,
    description: "",
    group: "backlog",
    name: "待办",
    project_id: "proj-2",
    sequence: 1,
    workspace_id: "ws-1",
    order: 1,
  },
  {
    id: "state-fa-2",
    color: "#6B7280",
    default: false,
    description: "",
    group: "unstarted",
    name: "未开始",
    project_id: "proj-2",
    sequence: 2,
    workspace_id: "ws-1",
    order: 2,
  },
  {
    id: "state-fa-3",
    color: "#F59E0B",
    default: false,
    description: "",
    group: "started",
    name: "开发中",
    project_id: "proj-2",
    sequence: 3,
    workspace_id: "ws-1",
    order: 3,
  },
  {
    id: "state-fa-4",
    color: "#3B82F6",
    default: false,
    description: "",
    group: "started",
    name: "测试中",
    project_id: "proj-2",
    sequence: 4,
    workspace_id: "ws-1",
    order: 4,
  },
  {
    id: "state-fa-5",
    color: "#10B981",
    default: false,
    description: "",
    group: "completed",
    name: "已完成",
    project_id: "proj-2",
    sequence: 5,
    workspace_id: "ws-1",
    order: 5,
  },
  {
    id: "state-fa-6",
    color: "#EF4444",
    default: false,
    description: "",
    group: "cancelled",
    name: "已取消",
    project_id: "proj-2",
    sequence: 6,
    workspace_id: "ws-1",
    order: 6,
  },
  {
    id: "state-fd-1",
    color: "#9CA3AF",
    default: true,
    description: "",
    group: "backlog",
    name: "待办",
    project_id: "proj-3",
    sequence: 1,
    workspace_id: "ws-1",
    order: 1,
  },
  {
    id: "state-fd-2",
    color: "#6B7280",
    default: false,
    description: "",
    group: "unstarted",
    name: "未开始",
    project_id: "proj-3",
    sequence: 2,
    workspace_id: "ws-1",
    order: 2,
  },
  {
    id: "state-fd-3",
    color: "#F59E0B",
    default: false,
    description: "",
    group: "started",
    name: "编写中",
    project_id: "proj-3",
    sequence: 3,
    workspace_id: "ws-1",
    order: 3,
  },
  {
    id: "state-fd-4",
    color: "#10B981",
    default: false,
    description: "",
    group: "completed",
    name: "已完成",
    project_id: "proj-3",
    sequence: 4,
    workspace_id: "ws-1",
    order: 4,
  },
  {
    id: "state-fd-5",
    color: "#EF4444",
    default: false,
    description: "",
    group: "cancelled",
    name: "已取消",
    project_id: "proj-3",
    sequence: 5,
    workspace_id: "ws-1",
    order: 5,
  },
];

// ---------------------------------------------------------------------------
// Labels (per D-P16-03)
// ---------------------------------------------------------------------------

export const MOCK_LABELS: IIssueLabel[] = [
  {
    id: "label-1",
    name: "Bug",
    color: "#EF4444",
    project_id: "proj-1",
    workspace_id: "ws-1",
    parent: null,
    sort_order: 1,
  },
  {
    id: "label-2",
    name: "增强",
    color: "#3B82F6",
    project_id: "proj-1",
    workspace_id: "ws-1",
    parent: null,
    sort_order: 2,
  },
  {
    id: "label-3",
    name: "UI",
    color: "#8B5CF6",
    project_id: "proj-1",
    workspace_id: "ws-1",
    parent: null,
    sort_order: 3,
  },
  {
    id: "label-4",
    name: "性能",
    color: "#F59E0B",
    project_id: "proj-1",
    workspace_id: "ws-1",
    parent: null,
    sort_order: 4,
  },
  {
    id: "label-5",
    name: "文档",
    color: "#10B981",
    project_id: "proj-1",
    workspace_id: "ws-1",
    parent: null,
    sort_order: 5,
  },
  {
    id: "label-6",
    name: "安全",
    color: "#EC4899",
    project_id: "proj-1",
    workspace_id: "ws-1",
    parent: null,
    sort_order: 6,
  },
  {
    id: "label-7",
    name: "Bug",
    color: "#EF4444",
    project_id: "proj-2",
    workspace_id: "ws-1",
    parent: null,
    sort_order: 1,
  },
  {
    id: "label-8",
    name: "API",
    color: "#3B82F6",
    project_id: "proj-2",
    workspace_id: "ws-1",
    parent: null,
    sort_order: 2,
  },
  {
    id: "label-9",
    name: "数据库",
    color: "#10B981",
    project_id: "proj-2",
    workspace_id: "ws-1",
    parent: null,
    sort_order: 3,
  },
  {
    id: "label-10",
    name: "单元测试",
    color: "#8B5CF6",
    project_id: "proj-2",
    workspace_id: "ws-1",
    parent: null,
    sort_order: 4,
  },
];

// ---------------------------------------------------------------------------
// Issues (per D-P16-03: 17 mock issues across 3 projects)
// ---------------------------------------------------------------------------

export const MOCK_ISSUES: TIssue[] = [
  {
    id: "issue-1",
    sequence_id: 1,
    name: "实现用户登录页面 UI",
    sort_order: 1,
    state_id: "state-ff-1",
    priority: "high",
    label_ids: ["label-3", "label-2"],
    assignee_ids: ["user-1", "user-2"],
    estimate_point: "5",
    sub_issues_count: 0,
    attachment_count: 0,
    link_count: 0,
    // FLOW: 关联 cycle-active-1 (Cycle 18 sprint)
    cycle_id: "cycle-active-1",
    project_id: "proj-1",
    parent_id: null,
    module_ids: null,
    type_id: null,
    created_at: new Date(now - dayMs * 3).toISOString(),
    updated_at: new Date(now - dayMs * 1).toISOString(),
    start_date: new Date(now - dayMs * 4).toISOString(),
    target_date: new Date(now + dayMs * 7).toISOString(),
    completed_at: null,
    archived_at: null,
    created_by: "user-1",
    updated_by: "user-2",
    is_draft: false,
    description_html: "<p>实现用户登录页面，包括邮箱密码输入框和登录按钮</p>",
    // FLOW: 添加 blocked_by 依赖用于甘特图 GANT-02 测试
    issue_relation: [
      { id: "issue-5", name: "实现后端认证 API", project_id: "proj-1", relation_type: "blocked_by", sequence_id: 5 },
    ],
  },
  {
    id: "issue-2",
    sequence_id: 2,
    name: "集成 JWT 认证流程",
    sort_order: 2,
    state_id: "state-ff-3",
    priority: "urgent",
    label_ids: ["label-4", "label-6"],
    assignee_ids: ["user-1"],
    estimate_point: "8",
    sub_issues_count: 2,
    attachment_count: 0,
    link_count: 0,
    // FLOW: 关联 cycle-active-1 (Cycle 18 sprint)
    cycle_id: "cycle-active-1",
    project_id: "proj-1",
    parent_id: null,
    module_ids: null,
    type_id: null,
    created_at: new Date(now - dayMs * 5).toISOString(),
    updated_at: new Date(now - dayMs * 2).toISOString(),
    start_date: new Date(now - dayMs * 2).toISOString(),
    target_date: new Date(now + dayMs * 3).toISOString(),
    completed_at: null,
    archived_at: null,
    created_by: "user-1",
    updated_by: "user-1",
    is_draft: false,
    description_html:
      "<p>集成 JWT 认证，包括 token 刷新和自动重试</p><ul><li>登录接口对接</li><li>Token 刷新逻辑</li><li>自动重试拦截器</li></ul>",
  },
  {
    id: "issue-3",
    sequence_id: 3,
    name: "修复表单验证错误提示不显示问题",
    sort_order: 3,
    state_id: "state-ff-5",
    priority: "medium",
    label_ids: ["label-1"],
    assignee_ids: ["user-2"],
    estimate_point: "3",
    sub_issues_count: 0,
    attachment_count: 0,
    link_count: 0,
    project_id: "proj-1",
    parent_id: null,
    cycle_id: null,
    module_ids: null,
    type_id: null,
    created_at: new Date(now - dayMs * 7).toISOString(),
    updated_at: new Date(now - dayMs * 4).toISOString(),
    start_date: null,
    target_date: null,
    completed_at: null,
    archived_at: new Date(now).toISOString(),
    created_by: "user-2",
    updated_by: "user-2",
    is_draft: false,
  },
  {
    id: "issue-4",
    sequence_id: 4,
    name: "优化首页加载性能",
    sort_order: 4,
    state_id: "state-ff-2",
    priority: "low",
    label_ids: ["label-4"],
    assignee_ids: [],
    estimate_point: "13",
    sub_issues_count: 0,
    attachment_count: 0,
    link_count: 0,
    // FLOW: 关联 mod-proj1-1 (用户认证模块)
    cycle_id: null,
    module_ids: ["mod-proj1-1"],
    project_id: "proj-1",
    parent_id: null,
    type_id: null,
    created_at: new Date(now - dayMs * 10).toISOString(),
    updated_at: new Date(now - dayMs * 8).toISOString(),
    // FLOW: 添加 start_date 用于甘特图显示
    start_date: new Date(now - dayMs * 6).toISOString(),
    target_date: new Date(now + dayMs * 14).toISOString(),
    completed_at: null,
    archived_at: null,
    created_by: "user-1",
    updated_by: "user-1",
    is_draft: false,
    description_html: "<p>首页加载时间超过 3 秒，需要优化组件懒加载和数据请求策略</p>",
    // FLOW: 添加 blocked_by 依赖用于甘特图 GANT-02 测试
    issue_relation: [
      { id: "issue-5", name: "实现后端认证 API", project_id: "proj-1", relation_type: "blocked_by", sequence_id: 5 },
    ],
  },
  {
    id: "issue-5",
    sequence_id: 5,
    name: "添加暗色模式支持",
    sort_order: 5,
    state_id: "state-ff-3",
    priority: "high",
    label_ids: ["label-3", "label-2"],
    assignee_ids: ["user-3"],
    estimate_point: "21",
    sub_issues_count: 3,
    attachment_count: 0,
    link_count: 0,
    // FLOW: 关联 cycle-active-1
    cycle_id: "cycle-active-1",
    project_id: "proj-1",
    parent_id: null,
    module_ids: null,
    type_id: null,
    created_at: new Date(now - dayMs * 14).toISOString(),
    updated_at: new Date(now - dayMs * 1).toISOString(),
    start_date: new Date(now - dayMs * 5).toISOString(),
    target_date: new Date(now + dayMs * 21).toISOString(),
    completed_at: null,
    archived_at: null,
    created_by: "user-3",
    updated_by: "user-3",
    is_draft: false,
    description_html: "<p>实现暗色模式切换功能，所有组件需要支持主题切换</p>",
  },
  {
    id: "issue-6",
    sequence_id: 6,
    name: "编写用户注册页面 E2E 测试",
    sort_order: 6,
    state_id: "state-ff-4",
    priority: "medium",
    label_ids: ["label-2"],
    assignee_ids: ["user-4"],
    estimate_point: "5",
    sub_issues_count: 0,
    attachment_count: 0,
    link_count: 0,
    project_id: "proj-1",
    parent_id: null,
    cycle_id: null,
    module_ids: null,
    type_id: null,
    created_at: new Date(now - dayMs * 6).toISOString(),
    updated_at: new Date(now - dayMs * 1).toISOString(),
    start_date: null,
    target_date: null,
    completed_at: new Date(now - dayMs * 1).toISOString(),
    archived_at: null,
    created_by: "user-1",
    updated_by: "user-1",
    is_draft: false,
  },
  {
    id: "issue-7",
    sequence_id: 7,
    name: "重构通知模块状态管理",
    sort_order: 7,
    state_id: "state-ff-3",
    priority: "low",
    label_ids: ["label-4"],
    assignee_ids: ["user-1", "user-2"],
    estimate_point: "13",
    sub_issues_count: 0,
    attachment_count: 0,
    link_count: 0,
    // FLOW: 关联 mod-proj1-1 和 mod-proj1-2
    project_id: "proj-1",
    parent_id: null,
    cycle_id: null,
    module_ids: ["mod-proj1-1", "mod-proj1-2"],
    type_id: null,
    created_at: new Date(now - dayMs * 2).toISOString(),
    updated_at: new Date(now - dayMs * 1).toISOString(),
    start_date: new Date(now - dayMs * 9).toISOString(),
    target_date: new Date(now - dayMs * 1).toISOString(),
    completed_at: null,
    archived_at: null,
    created_by: "user-2",
    updated_by: "user-2",
    is_draft: false,
    description_html: "<p>通知模块当前使用 MobX store，需要迁移到 TanStack Query</p>",
  },
  {
    id: "issue-8",
    sequence_id: 1,
    name: "设计 Issue 数据模型",
    sort_order: 1,
    state_id: "state-fa-4",
    priority: "urgent",
    label_ids: ["label-8", "label-9"],
    assignee_ids: ["user-1"],
    estimate_point: "8",
    sub_issues_count: 2,
    attachment_count: 0,
    link_count: 0,
    // FLOW: 关联 cycle-upcoming-1 (即将开始的 Cycle)
    project_id: "proj-2",
    parent_id: null,
    cycle_id: "cycle-upcoming-1",
    module_ids: null,
    type_id: null,
    created_at: new Date(now - dayMs * 15).toISOString(),
    updated_at: new Date(now - dayMs * 3).toISOString(),
    start_date: new Date(now - dayMs * 10).toISOString(),
    target_date: new Date(now - dayMs * 2).toISOString(),
    completed_at: null,
    archived_at: null,
    created_by: "user-1",
    updated_by: "user-3",
    is_draft: false,
    description_html: "<p>设计 Issue 数据的数据库模型和 API 接口定义</p><p>包括状态机、优先级、标签等字段</p>",
  },
  {
    id: "issue-9",
    sequence_id: 2,
    name: "实现 Issue CRUD API 端点",
    sort_order: 2,
    state_id: "state-fa-3",
    priority: "high",
    label_ids: ["label-8"],
    assignee_ids: ["user-3"],
    estimate_point: "13",
    sub_issues_count: 3,
    attachment_count: 0,
    link_count: 0,
    project_id: "proj-2",
    parent_id: null,
    cycle_id: null,
    // FLOW: 关联 mod-proj2-1 (Flow API Module)
    module_ids: ["mod-proj2-1"],
    type_id: null,
    created_at: new Date(now - dayMs * 12).toISOString(),
    updated_at: new Date(now).toISOString(),
    start_date: new Date(now - dayMs * 8).toISOString(),
    target_date: new Date(now + dayMs * 5).toISOString(),
    completed_at: null,
    archived_at: null,
    created_by: "user-3",
    updated_by: "user-3",
    is_draft: false,
    description_html: "<p>实现 Issue 的增删查改 API，包括分页和筛选支持</p>",
    // FLOW: 添加 blocked_by 依赖用于甘特图 GANT-02 测试
    issue_relation: [
      { id: "issue-8", name: "设计 Issue 数据模型", project_id: "proj-2", relation_type: "blocked_by", sequence_id: 1 },
      {
        id: "issue-10",
        name: "添加 API 版本控制和文档",
        project_id: "proj-2",
        relation_type: "blocked_by",
        sequence_id: 3,
      },
    ],
  },
  {
    id: "issue-10",
    sequence_id: 3,
    name: "添加 API 版本控制和文档",
    sort_order: 3,
    state_id: "state-fa-1",
    priority: "medium",
    label_ids: ["label-8", "label-10"],
    assignee_ids: [],
    estimate_point: "5",
    sub_issues_count: 0,
    attachment_count: 0,
    link_count: 0,
    project_id: "proj-2",
    parent_id: null,
    cycle_id: null,
    module_ids: null,
    type_id: null,
    created_at: new Date(now - dayMs * 8).toISOString(),
    updated_at: new Date(now - dayMs * 6).toISOString(),
    start_date: new Date(now - dayMs * 14).toISOString(),
    target_date: new Date(now + dayMs * 14).toISOString(),
    completed_at: null,
    archived_at: null,
    created_by: "user-1",
    updated_by: "user-1",
    is_draft: false,
    description_html: "<p>使用 OpenAPI/Scalar 生成 API 文档，确保版本控制策略</p>",
  },
  {
    id: "issue-11",
    sequence_id: 4,
    name: "修复并发请求导致的死锁问题",
    sort_order: 4,
    state_id: "state-fa-5",
    priority: "urgent",
    label_ids: ["label-7", "label-9"],
    assignee_ids: ["user-1"],
    estimate_point: "13",
    sub_issues_count: 0,
    attachment_count: 0,
    link_count: 0,
    project_id: "proj-2",
    parent_id: null,
    cycle_id: null,
    module_ids: null,
    type_id: null,
    created_at: new Date(now - dayMs * 4).toISOString(),
    updated_at: new Date(now - dayMs * 1).toISOString(),
    start_date: null,
    target_date: null,
    completed_at: new Date(now - dayMs * 1).toISOString(),
    archived_at: null,
    created_by: "user-1",
    updated_by: "user-1",
    is_draft: false,
    description_html: "<p>高并发下数据库连接池死锁，需要优化事务隔离级别</p>",
  },
  {
    id: "issue-12",
    sequence_id: 5,
    name: "实现缓存层（Redis）",
    sort_order: 5,
    state_id: "state-fa-2",
    priority: "high",
    label_ids: ["label-8", "label-4"],
    assignee_ids: ["user-3"],
    estimate_point: "8",
    sub_issues_count: 0,
    attachment_count: 0,
    link_count: 0,
    project_id: "proj-2",
    parent_id: null,
    cycle_id: null,
    module_ids: null,
    type_id: null,
    created_at: new Date(now - dayMs * 6).toISOString(),
    updated_at: new Date(now - dayMs * 2).toISOString(),
    start_date: new Date(now - dayMs * 3).toISOString(),
    target_date: new Date(now + dayMs * 10).toISOString(),
    completed_at: null,
    archived_at: null,
    created_by: "user-3",
    updated_by: "user-3",
    is_draft: false,
    description_html: "<p>实现 Redis 缓存层，缓存热点数据减少数据库压力</p>",
  },
  {
    id: "issue-13",
    sequence_id: 6,
    name: "为 API 添加请求速率限制",
    sort_order: 6,
    state_id: "state-fa-6",
    priority: "medium",
    label_ids: ["label-7", "label-8"],
    assignee_ids: ["user-1"],
    estimate_point: "5",
    sub_issues_count: 0,
    attachment_count: 0,
    link_count: 0,
    project_id: "proj-2",
    parent_id: null,
    cycle_id: null,
    module_ids: null,
    type_id: null,
    created_at: new Date(now - dayMs * 9).toISOString(),
    updated_at: new Date(now - dayMs * 7).toISOString(),
    start_date: null,
    target_date: null,
    completed_at: null,
    archived_at: new Date(now).toISOString(),
    created_by: "user-1",
    updated_by: "user-1",
    is_draft: false,
  },
  {
    id: "issue-14",
    sequence_id: 7,
    name: "编写单元测试覆盖核心业务逻辑",
    sort_order: 7,
    state_id: "state-fa-1",
    priority: "low",
    label_ids: ["label-10"],
    assignee_ids: ["user-5"],
    estimate_point: "21",
    sub_issues_count: 0,
    attachment_count: 0,
    link_count: 0,
    project_id: "proj-2",
    parent_id: null,
    cycle_id: null,
    module_ids: null,
    type_id: null,
    created_at: new Date(now - dayMs * 11).toISOString(),
    updated_at: new Date(now - dayMs * 9).toISOString(),
    start_date: new Date(now - dayMs * 1).toISOString(),
    target_date: new Date(now + dayMs * 30).toISOString(),
    completed_at: null,
    archived_at: null,
    created_by: "user-5",
    updated_by: "user-5",
    is_draft: false,
    // FLOW: 添加 blocked_by 依赖用于甘特图 GANT-02 测试
    issue_relation: [
      {
        id: "issue-12",
        name: "实现缓存层（Redis）",
        project_id: "proj-2",
        relation_type: "blocked_by",
        sequence_id: 5,
      },
    ],
  },
  {
    id: "issue-15",
    sequence_id: 1,
    name: "编写项目架构设计文档",
    sort_order: 1,
    state_id: "state-fd-4",
    priority: "high",
    label_ids: ["label-5"],
    assignee_ids: ["user-1"],
    estimate_point: "3",
    sub_issues_count: 0,
    attachment_count: 0,
    link_count: 0,
    project_id: "proj-3",
    parent_id: null,
    cycle_id: null,
    module_ids: null,
    type_id: null,
    created_at: new Date(now - dayMs * 20).toISOString(),
    updated_at: new Date(now - dayMs * 10).toISOString(),
    start_date: null,
    target_date: null,
    completed_at: new Date(now - dayMs * 10).toISOString(),
    archived_at: null,
    created_by: "user-1",
    updated_by: "user-1",
    is_draft: false,
    description_html: "<p>编写完整的项目架构设计文档，包括系统架构图、数据流图、技术选型说明</p>",
  },
  {
    id: "issue-16",
    sequence_id: 2,
    name: "撰写 API 集成指南",
    sort_order: 2,
    state_id: "state-fd-3",
    priority: "medium",
    label_ids: ["label-5"],
    assignee_ids: ["user-2"],
    estimate_point: "5",
    sub_issues_count: 0,
    attachment_count: 0,
    link_count: 0,
    project_id: "proj-3",
    parent_id: null,
    cycle_id: null,
    module_ids: null,
    type_id: null,
    created_at: new Date(now - dayMs * 12).toISOString(),
    updated_at: new Date(now - dayMs * 6).toISOString(),
    start_date: new Date(now - dayMs * 7).toISOString(),
    target_date: new Date(now + dayMs * 5).toISOString(),
    completed_at: null,
    archived_at: null,
    created_by: "user-2",
    updated_by: "user-2",
    is_draft: false,
    description_html: "<p>撰写面向开发者的 API 集成指南，包含示例代码和最佳实践</p>",
  },
  {
    id: "issue-17",
    sequence_id: 3,
    name: "更新 README 和贡献指南",
    sort_order: 3,
    state_id: "state-fd-1",
    priority: "low",
    label_ids: ["label-5"],
    assignee_ids: [],
    estimate_point: "2",
    sub_issues_count: 0,
    attachment_count: 0,
    link_count: 0,
    project_id: "proj-3",
    parent_id: null,
    cycle_id: null,
    module_ids: null,
    type_id: null,
    created_at: new Date(now - dayMs * 5).toISOString(),
    updated_at: new Date(now - dayMs * 3).toISOString(),
    start_date: null,
    target_date: null,
    completed_at: null,
    archived_at: null,
    created_by: "user-1",
    updated_by: "user-1",
    is_draft: false,
  },
];

// ---------------------------------------------------------------------------
// Issue Comments (per RESEARCH.md — 3-5 comments per issue)
// ---------------------------------------------------------------------------

export const MOCK_ISSUE_COMMENTS: TIssueComment[] = [
  {
    id: "comment-1",
    workspace: "ws-1",
    project: "proj-1",
    issue: "issue-1",
    actor: "user-2",
    actor_detail: {
      id: "user-2",
      first_name: "李四",
      last_name: "",
      avatar_url: "",
      is_bot: false,
      display_name: "李四",
    },
    created_at: new Date(now - dayMs * 2).toISOString(),
    updated_at: new Date(now - dayMs * 2).toISOString(),
    created_by: "user-2",
    updated_by: "user-2",
    attachments: [],
    comment_reactions: [],
    comment_stripped: "好的，我来负责 UI 部分",
    comment_html: "<p>好的，我来负责 UI 部分</p>",
    comment_json: {
      type: "doc",
      content: [{ type: "paragraph", content: [{ type: "text", text: "好的，我来负责 UI 部分" }] }],
    } as any,
    external_id: undefined,
    external_source: undefined,
    access: "INTERNAL" as any,
    workspace_detail: { id: "ws-1", name: "Flow 开发组", slug: "flow-dev" },
    project_detail: {
      id: "proj-1",
      identifier: "FF",
      name: "Flow 前端",
      cover_image: "",
      description: null,
      emoji: null,
      icon_prop: null,
    },
    issue_detail: {
      id: "issue-1",
      sequence_id: 1,
      sort_order: false as any,
      name: "实现用户登录页面 UI",
      description_html: "",
      priority: "high" as any,
      start_date: "",
      target_date: "",
      is_draft: false,
    },
    edited_at: undefined,
  },
  {
    id: "comment-2",
    workspace: "ws-1",
    project: "proj-1",
    issue: "issue-1",
    actor: "user-1",
    actor_detail: {
      id: "user-1",
      first_name: "张三",
      last_name: "",
      avatar_url: "",
      is_bot: false,
      display_name: "张三",
    },
    created_at: new Date(now - dayMs * 1).toISOString(),
    updated_at: new Date(now - dayMs * 1).toISOString(),
    created_by: "user-1",
    updated_by: "user-1",
    attachments: [],
    comment_reactions: [],
    comment_stripped: "我已经完成了登录表单的布局，请 review",
    comment_html: "<p>我已经完成了登录表单的布局，请 review</p>",
    comment_json: {
      type: "doc",
      content: [{ type: "paragraph", content: [{ type: "text", text: "我已经完成了登录表单的布局，请 review" }] }],
    } as any,
    external_id: undefined,
    external_source: undefined,
    access: "INTERNAL" as any,
    workspace_detail: { id: "ws-1", name: "Flow 开发组", slug: "flow-dev" },
    project_detail: {
      id: "proj-1",
      identifier: "FF",
      name: "Flow 前端",
      cover_image: "",
      description: null,
      emoji: null,
      icon_prop: null,
    },
    issue_detail: {
      id: "issue-1",
      sequence_id: 1,
      sort_order: false as any,
      name: "实现用户登录页面 UI",
      description_html: "",
      priority: "high" as any,
      start_date: "",
      target_date: "",
      is_draft: false,
    },
    edited_at: undefined,
  },
  {
    id: "comment-3",
    workspace: "ws-1",
    project: "proj-1",
    issue: "issue-2",
    actor: "user-3",
    actor_detail: {
      id: "user-3",
      first_name: "王五",
      last_name: "",
      avatar_url: "",
      is_bot: false,
      display_name: "王五",
    },
    created_at: new Date(now - dayMs * 3).toISOString(),
    updated_at: new Date(now - dayMs * 2).toISOString(),
    created_by: "user-3",
    updated_by: "user-3",
    attachments: [],
    comment_reactions: [],
    comment_stripped: "JWT 刷新逻辑我建议使用 axios 拦截器实现",
    comment_html: "<p>JWT 刷新逻辑我建议使用 axios 拦截器实现</p>",
    comment_json: {
      type: "doc",
      content: [{ type: "paragraph", content: [{ type: "text", text: "JWT 刷新逻辑我建议使用 axios 拦截器实现" }] }],
    } as any,
    external_id: undefined,
    external_source: undefined,
    access: "INTERNAL" as any,
    workspace_detail: { id: "ws-1", name: "Flow 开发组", slug: "flow-dev" },
    project_detail: {
      id: "proj-1",
      identifier: "FF",
      name: "Flow 前端",
      cover_image: "",
      description: null,
      emoji: null,
      icon_prop: null,
    },
    issue_detail: {
      id: "issue-2",
      sequence_id: 2,
      sort_order: false as any,
      name: "集成 JWT 认证流程",
      description_html: "",
      priority: "urgent" as any,
      start_date: "",
      target_date: "",
      is_draft: false,
    },
    edited_at: new Date(now - dayMs * 2).toISOString(),
  },
  {
    id: "comment-4",
    workspace: "ws-1",
    project: "proj-1",
    issue: "issue-5",
    actor: "user-1",
    actor_detail: {
      id: "user-1",
      first_name: "张三",
      last_name: "",
      avatar_url: "",
      is_bot: false,
      display_name: "张三",
    },
    created_at: new Date(now - dayMs * 5).toISOString(),
    updated_at: new Date(now - dayMs * 5).toISOString(),
    created_by: "user-1",
    updated_by: "user-1",
    attachments: [],
    comment_reactions: [],
    comment_stripped: "暗色模式的配色方案已共享到设计团队，请查收",
    comment_html: "<p>暗色模式的配色方案已共享到设计团队，请查收</p>",
    comment_json: {
      type: "doc",
      content: [{ type: "paragraph", content: [{ type: "text", text: "暗色模式的配色方案已共享到设计团队，请查收" }] }],
    } as any,
    external_id: undefined,
    external_source: undefined,
    access: "INTERNAL" as any,
    workspace_detail: { id: "ws-1", name: "Flow 开发组", slug: "flow-dev" },
    project_detail: {
      id: "proj-1",
      identifier: "FF",
      name: "Flow 前端",
      cover_image: "",
      description: null,
      emoji: null,
      icon_prop: null,
    },
    issue_detail: {
      id: "issue-5",
      sequence_id: 5,
      sort_order: false as any,
      name: "添加暗色模式支持",
      description_html: "",
      priority: "high" as any,
      start_date: "",
      target_date: "",
      is_draft: false,
    },
    edited_at: undefined,
  },
  {
    id: "comment-5",
    workspace: "ws-1",
    project: "proj-1",
    issue: "issue-5",
    actor: "user-3",
    actor_detail: {
      id: "user-3",
      first_name: "王五",
      last_name: "",
      avatar_url: "",
      is_bot: false,
      display_name: "王五",
    },
    created_at: new Date(now - dayMs * 3).toISOString(),
    updated_at: new Date(now - dayMs * 3).toISOString(),
    created_by: "user-3",
    updated_by: "user-3",
    attachments: [],
    comment_reactions: [],
    comment_stripped: "已收到，我会在一周内完成所有组件的适配",
    comment_html: "<p>已收到，我会在一周内完成所有组件的适配</p>",
    comment_json: {
      type: "doc",
      content: [{ type: "paragraph", content: [{ type: "text", text: "已收到，我会在一周内完成所有组件的适配" }] }],
    } as any,
    external_id: undefined,
    external_source: undefined,
    access: "INTERNAL" as any,
    workspace_detail: { id: "ws-1", name: "Flow 开发组", slug: "flow-dev" },
    project_detail: {
      id: "proj-1",
      identifier: "FF",
      name: "Flow 前端",
      cover_image: "",
      description: null,
      emoji: null,
      icon_prop: null,
    },
    issue_detail: {
      id: "issue-5",
      sequence_id: 5,
      sort_order: false as any,
      name: "添加暗色模式支持",
      description_html: "",
      priority: "high" as any,
      start_date: "",
      target_date: "",
      is_draft: false,
    },
    edited_at: undefined,
  },
  {
    id: "comment-6",
    workspace: "ws-1",
    project: "proj-1",
    issue: "issue-7",
    actor: "user-2",
    actor_detail: {
      id: "user-2",
      first_name: "李四",
      last_name: "",
      avatar_url: "",
      is_bot: false,
      display_name: "李四",
    },
    created_at: new Date(now - dayMs * 1).toISOString(),
    updated_at: new Date(now - dayMs * 1).toISOString(),
    created_by: "user-2",
    updated_by: "user-2",
    attachments: [],
    comment_reactions: [],
    comment_stripped: "当前 MobX 和 TanStack Query 数据存在同步问题，需要优先解决",
    comment_html: "<p>当前 MobX 和 TanStack Query 数据存在同步问题，需要优先解决</p>",
    comment_json: {
      type: "doc",
      content: [
        { type: "paragraph", content: [{ type: "text", text: "当前 MobX 和 TanStack Query 数据存在同步问题" }] },
      ],
    } as any,
    external_id: undefined,
    external_source: undefined,
    access: "INTERNAL" as any,
    workspace_detail: { id: "ws-1", name: "Flow 开发组", slug: "flow-dev" },
    project_detail: {
      id: "proj-1",
      identifier: "FF",
      name: "Flow 前端",
      cover_image: "",
      description: null,
      emoji: null,
      icon_prop: null,
    },
    issue_detail: {
      id: "issue-7",
      sequence_id: 7,
      sort_order: false as any,
      name: "重构通知模块状态管理",
      description_html: "",
      priority: "low" as any,
      start_date: "",
      target_date: "",
      is_draft: false,
    },
    edited_at: undefined,
  },
];

// ---------------------------------------------------------------------------
// Issue Activities (for activity log — per RESEARCH.md)
// ---------------------------------------------------------------------------

export const MOCK_ISSUE_ACTIVITIES: TIssueActivity[] = [
  {
    id: "iact-1",
    workspace: "ws-1",
    project: "proj-1",
    issue: "issue-1",
    actor: "user-1",
    actor_detail: {
      id: "user-1",
      first_name: "张三",
      last_name: "",
      avatar_url: "",
      is_bot: false,
      display_name: "张三",
    },
    created_at: new Date(now - dayMs * 3).toISOString(),
    updated_at: new Date(now - dayMs * 3).toISOString(),
    created_by: "user-1",
    updated_by: "user-1",
    attachments: [],
    verb: "created",
    field: "name",
    old_value: undefined,
    new_value: undefined,
    old_identifier: undefined,
    new_identifier: undefined,
    comment: undefined,
    epoch: now - dayMs * 3,
    issue_comment: null,
    workspace_detail: { id: "ws-1", name: "Flow 开发组", slug: "flow-dev" },
    project_detail: {
      id: "proj-1",
      identifier: "FF",
      name: "Flow 前端",
      cover_image: "",
      description: null,
      emoji: null,
      icon_prop: null,
    },
    issue_detail: {
      id: "issue-1",
      sequence_id: 1,
      sort_order: false as any,
      name: "实现用户登录页面 UI",
      description_html: "",
      priority: "high" as any,
      start_date: "",
      target_date: "",
      is_draft: false,
    },
    source_data: { source: "web" as any, extra: {} },
  },
  {
    id: "iact-2",
    workspace: "ws-1",
    project: "proj-1",
    issue: "issue-1",
    actor: "user-2",
    actor_detail: {
      id: "user-2",
      first_name: "李四",
      last_name: "",
      avatar_url: "",
      is_bot: false,
      display_name: "李四",
    },
    created_at: new Date(now - dayMs * 2).toISOString(),
    updated_at: new Date(now - dayMs * 2).toISOString(),
    created_by: "user-2",
    updated_by: "user-2",
    attachments: [],
    verb: "updated",
    field: "state",
    old_value: "待办 (state-ff-1)",
    new_value: "进行中 (state-ff-3)",
    old_identifier: undefined,
    new_identifier: undefined,
    comment: undefined,
    epoch: now - dayMs * 2,
    issue_comment: null,
    workspace_detail: { id: "ws-1", name: "Flow 开发组", slug: "flow-dev" },
    project_detail: {
      id: "proj-1",
      identifier: "FF",
      name: "Flow 前端",
      cover_image: "",
      description: null,
      emoji: null,
      icon_prop: null,
    },
    issue_detail: {
      id: "issue-1",
      sequence_id: 1,
      sort_order: false as any,
      name: "实现用户登录页面 UI",
      description_html: "",
      priority: "high" as any,
      start_date: "",
      target_date: "",
      is_draft: false,
    },
    source_data: { source: "web" as any, extra: {} },
  },
  {
    id: "iact-3",
    workspace: "ws-1",
    project: "proj-1",
    issue: "issue-1",
    actor: "user-1",
    actor_detail: {
      id: "user-1",
      first_name: "张三",
      last_name: "",
      avatar_url: "",
      is_bot: false,
      display_name: "张三",
    },
    created_at: new Date(now - dayMs * 1).toISOString(),
    updated_at: new Date(now - dayMs * 1).toISOString(),
    created_by: "user-1",
    updated_by: "user-1",
    attachments: [],
    verb: "updated",
    field: "priority",
    old_value: "medium",
    new_value: "high",
    old_identifier: undefined,
    new_identifier: undefined,
    comment: undefined,
    epoch: now - dayMs * 1,
    issue_comment: null,
    workspace_detail: { id: "ws-1", name: "Flow 开发组", slug: "flow-dev" },
    project_detail: {
      id: "proj-1",
      identifier: "FF",
      name: "Flow 前端",
      cover_image: "",
      description: null,
      emoji: null,
      icon_prop: null,
    },
    issue_detail: {
      id: "issue-1",
      sequence_id: 1,
      sort_order: false as any,
      name: "实现用户登录页面 UI",
      description_html: "",
      priority: "high" as any,
      start_date: "",
      target_date: "",
      is_draft: false,
    },
    source_data: { source: "web" as any, extra: {} },
  },
  {
    id: "iact-4",
    workspace: "ws-1",
    project: "proj-1",
    issue: "issue-1",
    actor: "user-2",
    actor_detail: {
      id: "user-2",
      first_name: "李四",
      last_name: "",
      avatar_url: "",
      is_bot: false,
      display_name: "李四",
    },
    created_at: new Date(now - dayMs * 1).toISOString(),
    updated_at: new Date(now - dayMs * 1).toISOString(),
    created_by: "user-2",
    updated_by: "user-2",
    attachments: [],
    verb: "updated",
    field: "description",
    old_value: undefined,
    new_value: undefined,
    old_identifier: undefined,
    new_identifier: undefined,
    comment: "更新了 Issue 描述",
    epoch: now - dayMs * 1,
    issue_comment: null,
    workspace_detail: { id: "ws-1", name: "Flow 开发组", slug: "flow-dev" },
    project_detail: {
      id: "proj-1",
      identifier: "FF",
      name: "Flow 前端",
      cover_image: "",
      description: null,
      emoji: null,
      icon_prop: null,
    },
    issue_detail: {
      id: "issue-1",
      sequence_id: 1,
      sort_order: false as any,
      name: "实现用户登录页面 UI",
      description_html: "",
      priority: "high" as any,
      start_date: "",
      target_date: "",
      is_draft: false,
    },
    source_data: { source: "web" as any, extra: {} },
  },
  {
    id: "iact-5",
    workspace: "ws-1",
    project: "proj-1",
    issue: "issue-1",
    actor: "user-3",
    actor_detail: {
      id: "user-3",
      first_name: "王五",
      last_name: "",
      avatar_url: "",
      is_bot: false,
      display_name: "王五",
    },
    created_at: new Date(now).toISOString(),
    updated_at: new Date(now).toISOString(),
    created_by: "user-3",
    updated_by: "user-3",
    attachments: [],
    verb: "updated",
    field: "assignee",
    old_value: "",
    new_value: "user-3",
    old_identifier: undefined,
    new_identifier: undefined,
    comment: undefined,
    epoch: now,
    issue_comment: null,
    workspace_detail: { id: "ws-1", name: "Flow 开发组", slug: "flow-dev" },
    project_detail: {
      id: "proj-1",
      identifier: "FF",
      name: "Flow 前端",
      cover_image: "",
      description: null,
      emoji: null,
      icon_prop: null,
    },
    issue_detail: {
      id: "issue-1",
      sequence_id: 1,
      sort_order: false as any,
      name: "实现用户登录页面 UI",
      description_html: "",
      priority: "high" as any,
      start_date: "",
      target_date: "",
      is_draft: false,
    },
    source_data: { source: "web" as any, extra: {} },
  },
  {
    id: "iact-6",
    workspace: "ws-1",
    project: "proj-2",
    issue: "issue-8",
    actor: "user-1",
    actor_detail: {
      id: "user-1",
      first_name: "张三",
      last_name: "",
      avatar_url: "",
      is_bot: false,
      display_name: "张三",
    },
    created_at: new Date(now - dayMs * 15).toISOString(),
    updated_at: new Date(now - dayMs * 15).toISOString(),
    created_by: "user-1",
    updated_by: "user-1",
    attachments: [],
    verb: "created",
    field: "name",
    old_value: undefined,
    new_value: undefined,
    old_identifier: undefined,
    new_identifier: undefined,
    comment: undefined,
    epoch: now - dayMs * 15,
    issue_comment: null,
    workspace_detail: { id: "ws-1", name: "Flow 开发组", slug: "flow-dev" },
    project_detail: {
      id: "proj-2",
      identifier: "FA",
      name: "Flow API",
      cover_image: "",
      description: null,
      emoji: null,
      icon_prop: null,
    },
    issue_detail: {
      id: "issue-8",
      sequence_id: 1,
      sort_order: false as any,
      name: "设计 Issue 数据模型",
      description_html: "",
      priority: "urgent" as any,
      start_date: "",
      target_date: "",
      is_draft: false,
    },
    source_data: { source: "web" as any, extra: {} },
  },
  {
    id: "iact-7",
    workspace: "ws-1",
    project: "proj-2",
    issue: "issue-8",
    actor: "user-3",
    actor_detail: {
      id: "user-3",
      first_name: "王五",
      last_name: "",
      avatar_url: "",
      is_bot: false,
      display_name: "王五",
    },
    created_at: new Date(now - dayMs * 12).toISOString(),
    updated_at: new Date(now - dayMs * 12).toISOString(),
    created_by: "user-3",
    updated_by: "user-3",
    attachments: [],
    verb: "updated",
    field: "assignee",
    old_value: "",
    new_value: "user-3",
    old_identifier: undefined,
    new_identifier: undefined,
    comment: undefined,
    epoch: now - dayMs * 12,
    issue_comment: null,
    workspace_detail: { id: "ws-1", name: "Flow 开发组", slug: "flow-dev" },
    project_detail: {
      id: "proj-2",
      identifier: "FA",
      name: "Flow API",
      cover_image: "",
      description: null,
      emoji: null,
      icon_prop: null,
    },
    issue_detail: {
      id: "issue-8",
      sequence_id: 1,
      sort_order: false as any,
      name: "设计 Issue 数据模型",
      description_html: "",
      priority: "urgent" as any,
      start_date: "",
      target_date: "",
      is_draft: false,
    },
    source_data: { source: "web" as any, extra: {} },
  },
  {
    id: "iact-8",
    workspace: "ws-1",
    project: "proj-1",
    issue: "issue-5",
    actor: "user-1",
    actor_detail: {
      id: "user-1",
      first_name: "张三",
      last_name: "",
      avatar_url: "",
      is_bot: false,
      display_name: "张三",
    },
    created_at: new Date(now - dayMs * 10).toISOString(),
    updated_at: new Date(now - dayMs * 10).toISOString(),
    created_by: "user-1",
    updated_by: "user-1",
    attachments: [],
    verb: "created",
    field: "name",
    old_value: undefined,
    new_value: undefined,
    old_identifier: undefined,
    new_identifier: undefined,
    comment: undefined,
    epoch: now - dayMs * 10,
    issue_comment: null,
    workspace_detail: { id: "ws-1", name: "Flow 开发组", slug: "flow-dev" },
    project_detail: {
      id: "proj-1",
      identifier: "FF",
      name: "Flow 前端",
      cover_image: "",
      description: null,
      emoji: null,
      icon_prop: null,
    },
    issue_detail: {
      id: "issue-5",
      sequence_id: 5,
      sort_order: false as any,
      name: "添加暗色模式支持",
      description_html: "",
      priority: "high" as any,
      start_date: "",
      target_date: "",
      is_draft: false,
    },
    source_data: { source: "web" as any, extra: {} },
  },
];

// Dict form for useComments lookup
export const MOCK_COMMENTS: Record<string, TIssueComment[]> = MOCK_ISSUE_COMMENTS.reduce(
  (acc, c) => {
    const key = c.issue;
    if (!acc[key]) acc[key] = [];
    acc[key].push(c);
    return acc;
  },
  {} as Record<string, TIssueComment[]>
);

// ---------------------------------------------------------------------------
// Cycles (per D-P18-04: 5+ mock cycles across proj-1 and proj-2)
// ---------------------------------------------------------------------------

const nowCycles = Date.now();
const dayMsC = 86400 * 1000;

export const MOCK_CYCLES: ICycle[] = [
  {
    // 当前活跃周期 — Sprint 14
    id: "cycle-active-1",
    name: "Sprint 14",
    description: "前端核心功能冲刺：登录、暗色模式、JWT 集成",
    start_date: new Date(nowCycles - dayMsC * 14).toISOString(),
    end_date: new Date(nowCycles + dayMsC * 14).toISOString(),
    status: "current",
    sort_order: 10000,
    project_id: "proj-1",
    workspace_id: "ws-1",
    owned_by_id: "user-1",
    created_by: "user-1",
    created_at: new Date(nowCycles - dayMsC * 14).toISOString(),
    updated_at: new Date(nowCycles).toISOString(),
    updated_by: "user-1",
    archived_at: null,
    assignee_ids: ["user-1", "user-2", "user-3"],
    view_props: { filters: {} },
    project_detail: { id: "proj-1" },
    progress: [],
    version: 1,
    is_favorite: true,

    // TProgressSnapshot fields
    total_issues: 8,
    completed_issues: 2,
    backlog_issues: 1,
    started_issues: 3,
    unstarted_issues: 1,
    cancelled_issues: 1,
    backlog_estimate_points: 3,
    started_estimate_points: 21,
    unstarted_estimate_points: 5,
    cancelled_estimate_points: 5,
    total_estimate_points: 50,
    completed_estimate_points: 13,
    progress_snapshot: {
      total_issues: 8,
      completed_issues: 2,
      backlog_issues: 1,
      started_issues: 3,
      unstarted_issues: 1,
      cancelled_issues: 1,
      backlog_estimate_points: 3,
      started_estimate_points: 21,
      unstarted_estimate_points: 5,
      cancelled_estimate_points: 5,
      total_estimate_points: 50,
      completed_estimate_points: 13,
      distribution: {
        assignees: [
          {
            assignee_id: "user-1",
            avatar_url: null,
            first_name: "张三",
            last_name: null,
            display_name: "张三",
            total_issues: 4,
            pending_issues: 3,
            completed_issues: 1,
          },
          {
            assignee_id: "user-2",
            avatar_url: null,
            first_name: "李四",
            last_name: null,
            display_name: "李四",
            total_issues: 3,
            pending_issues: 2,
            completed_issues: 1,
          },
          {
            assignee_id: "user-3",
            avatar_url: null,
            first_name: "王五",
            last_name: null,
            display_name: "王五",
            total_issues: 1,
            pending_issues: 1,
            completed_issues: 0,
          },
        ],
        completion_chart: {},
        labels: [],
      },
    },
  },
  {
    // 即将开始的周期 — 迭代 15
    id: "cycle-upcoming-1",
    name: "迭代 15",
    description: "API 对接与性能优化",
    start_date: new Date(nowCycles + dayMsC * 15).toISOString(),
    end_date: new Date(nowCycles + dayMsC * 42).toISOString(),
    status: "upcoming",
    sort_order: 20000,
    project_id: "proj-1",
    workspace_id: "ws-1",
    owned_by_id: "user-1",
    created_by: "user-1",
    created_at: new Date(nowCycles - dayMsC * 1).toISOString(),
    updated_at: new Date(nowCycles).toISOString(),
    updated_by: "user-1",
    archived_at: null,
    assignee_ids: ["user-1", "user-3"],
    view_props: { filters: {} },
    project_detail: { id: "proj-1" },
    progress: [],
    version: 1,

    // TProgressSnapshot fields (no issues yet)
    total_issues: 0,
    completed_issues: 0,
    backlog_issues: 0,
    started_issues: 0,
    unstarted_issues: 0,
    cancelled_issues: 0,
    backlog_estimate_points: 0,
    started_estimate_points: 0,
    unstarted_estimate_points: 0,
    cancelled_estimate_points: 0,
    progress_snapshot: undefined,
  },
  {
    // 已完成周期 — Sprint 12
    id: "cycle-completed-1",
    name: "Sprint 12",
    description: "基础框架搭建：项目脚手架、路由、状态管理",
    start_date: new Date(nowCycles - dayMsC * 60).toISOString(),
    end_date: new Date(nowCycles - dayMsC * 46).toISOString(),
    status: "completed",
    sort_order: 30000,
    project_id: "proj-1",
    workspace_id: "ws-1",
    owned_by_id: "user-1",
    created_by: "user-1",
    created_at: new Date(nowCycles - dayMsC * 60).toISOString(),
    updated_at: new Date(nowCycles - dayMsC * 46).toISOString(),
    updated_by: "user-1",
    archived_at: null,
    assignee_ids: ["user-1", "user-2"],
    view_props: { filters: {} },
    project_detail: { id: "proj-1" },
    progress: [],
    version: 1,
    is_favorite: false,

    total_issues: 12,
    completed_issues: 11,
    backlog_issues: 0,
    started_issues: 0,
    unstarted_issues: 0,
    cancelled_issues: 1,
    backlog_estimate_points: 0,
    started_estimate_points: 0,
    unstarted_estimate_points: 0,
    cancelled_estimate_points: 3,
    total_estimate_points: 80,
    completed_estimate_points: 77,
    progress_snapshot: {
      total_issues: 12,
      completed_issues: 11,
      backlog_issues: 0,
      started_issues: 0,
      unstarted_issues: 0,
      cancelled_issues: 1,
      backlog_estimate_points: 0,
      started_estimate_points: 0,
      unstarted_estimate_points: 0,
      cancelled_estimate_points: 3,
      total_estimate_points: 80,
      completed_estimate_points: 77,
    },
  },
  {
    // 已完成周期 — Sprint 13
    id: "cycle-completed-2",
    name: "Sprint 13",
    description: "工作区 & 项目管理功能开发",
    start_date: new Date(nowCycles - dayMsC * 45).toISOString(),
    end_date: new Date(nowCycles - dayMsC * 31).toISOString(),
    status: "completed",
    sort_order: 40000,
    project_id: "proj-1",
    workspace_id: "ws-1",
    owned_by_id: "user-1",
    created_by: "user-1",
    created_at: new Date(nowCycles - dayMsC * 45).toISOString(),
    updated_at: new Date(nowCycles - dayMsC * 31).toISOString(),
    updated_by: "user-1",
    archived_at: null,
    assignee_ids: ["user-1", "user-2", "user-3", "user-4"],
    view_props: { filters: {} },
    project_detail: { id: "proj-1" },
    progress: [],
    version: 1,
    is_favorite: false,

    total_issues: 15,
    completed_issues: 14,
    backlog_issues: 0,
    started_issues: 0,
    unstarted_issues: 0,
    cancelled_issues: 1,
    backlog_estimate_points: 0,
    started_estimate_points: 0,
    unstarted_estimate_points: 0,
    cancelled_estimate_points: 5,
    total_estimate_points: 95,
    completed_estimate_points: 90,
    progress_snapshot: {
      total_issues: 15,
      completed_issues: 14,
      backlog_issues: 0,
      started_issues: 0,
      unstarted_issues: 0,
      cancelled_issues: 1,
      backlog_estimate_points: 0,
      started_estimate_points: 0,
      unstarted_estimate_points: 0,
      cancelled_estimate_points: 5,
      total_estimate_points: 95,
      completed_estimate_points: 90,
    },
  },
  {
    // 草稿周期 — 未命名草案
    id: "cycle-draft-1",
    name: "新迭代计划",
    description: "待计划的下个迭代内容草案",
    start_date: null,
    end_date: null,
    status: "draft",
    sort_order: 50000,
    project_id: "proj-2",
    workspace_id: "ws-1",
    owned_by_id: "user-3",
    created_by: "user-3",
    created_at: new Date(nowCycles - dayMsC * 2).toISOString(),
    updated_at: new Date(nowCycles - dayMsC * 2).toISOString(),
    updated_by: "user-3",
    archived_at: null,
    assignee_ids: [],
    view_props: { filters: {} },
    project_detail: { id: "proj-2" },
    progress: [],
    version: 1,

    total_issues: 0,
    completed_issues: 0,
    backlog_issues: 0,
    started_issues: 0,
    unstarted_issues: 0,
    cancelled_issues: 0,
    backlog_estimate_points: 0,
    started_estimate_points: 0,
    unstarted_estimate_points: 0,
    cancelled_estimate_points: 0,
    progress_snapshot: undefined,
  },
];

// ---------------------------------------------------------------------------
// Modules (per D-P18-05: 4+ mock modules across proj-1 and proj-2)
// ---------------------------------------------------------------------------

export const MOCK_MODULES: IModule[] = [
  {
    id: "mod-proj1-1",
    name: "用户认证模块",
    description: "登录、注册、JWT 令牌管理、OAuth 集成",
    description_text: null,
    description_html: null,
    workspace_id: "ws-1",
    project_id: "proj-1",
    lead_id: "user-1",
    member_ids: ["user-1", "user-2"],
    is_favorite: true,
    sort_order: 10000,
    view_props: { filters: {} },
    status: "in-progress",
    archived_at: null,
    start_date: new Date(nowCycles - dayMsC * 20).toISOString(),
    target_date: new Date(nowCycles + dayMsC * 10).toISOString(),
    created_at: new Date(nowCycles - dayMsC * 20).toISOString(),
    updated_at: new Date(nowCycles).toISOString(),
    created_by: "user-1",
    updated_by: "user-1",

    total_issues: 5,
    completed_issues: 1,
    backlog_issues: 1,
    started_issues: 2,
    unstarted_issues: 1,
    cancelled_issues: 0,
    backlog_estimate_points: 3,
    started_estimate_points: 21,
    unstarted_estimate_points: 13,
    cancelled_estimate_points: 0,
    total_estimate_points: 37,
    completed_estimate_points: 5,
  },
  {
    id: "mod-proj1-2",
    name: "UI 重构",
    description: "暗色模式、响应式布局、组件库升级",
    description_text: null,
    description_html: null,
    workspace_id: "ws-1",
    project_id: "proj-1",
    lead_id: "user-2",
    member_ids: ["user-2", "user-3"],
    is_favorite: false,
    sort_order: 20000,
    view_props: { filters: {} },
    status: "planned",
    archived_at: null,
    start_date: new Date(nowCycles + dayMsC * 7).toISOString(),
    target_date: new Date(nowCycles + dayMsC * 35).toISOString(),
    created_at: new Date(nowCycles - dayMsC * 10).toISOString(),
    updated_at: new Date(nowCycles).toISOString(),
    created_by: "user-2",
    updated_by: "user-2",

    total_issues: 3,
    completed_issues: 0,
    backlog_issues: 2,
    started_issues: 0,
    unstarted_issues: 1,
    cancelled_issues: 0,
    backlog_estimate_points: 8,
    started_estimate_points: 0,
    unstarted_estimate_points: 21,
    cancelled_estimate_points: 0,
    total_estimate_points: 29,
    completed_estimate_points: 0,
  },
  {
    id: "mod-proj1-3",
    name: "性能优化",
    description: "首页加载优化、组件懒加载、缓存策略",
    description_text: null,
    description_html: null,
    workspace_id: "ws-1",
    project_id: "proj-1",
    lead_id: "user-1",
    member_ids: ["user-1"],
    is_favorite: false,
    sort_order: 30000,
    view_props: { filters: {} },
    status: "completed",
    archived_at: null,
    start_date: new Date(nowCycles - dayMsC * 30).toISOString(),
    target_date: new Date(nowCycles - dayMsC * 5).toISOString(),
    created_at: new Date(nowCycles - dayMsC * 30).toISOString(),
    updated_at: new Date(nowCycles - dayMsC * 5).toISOString(),
    created_by: "user-1",
    updated_by: "user-1",

    total_issues: 4,
    completed_issues: 4,
    backlog_issues: 0,
    started_issues: 0,
    unstarted_issues: 0,
    cancelled_issues: 0,
    backlog_estimate_points: 0,
    started_estimate_points: 0,
    unstarted_estimate_points: 0,
    cancelled_estimate_points: 0,
    total_estimate_points: 20,
    completed_estimate_points: 20,
  },
  {
    id: "mod-proj2-1",
    name: "Flow API 核心",
    description: "API CRUD、缓存、测试覆盖",
    description_text: null,
    description_html: null,
    workspace_id: "ws-1",
    project_id: "proj-2",
    lead_id: "user-3",
    member_ids: ["user-3", "user-1"],
    is_favorite: true,
    sort_order: 10000,
    view_props: { filters: {} },
    status: "in-progress",
    archived_at: null,
    start_date: new Date(nowCycles - dayMsC * 15).toISOString(),
    target_date: new Date(nowCycles + dayMsC * 20).toISOString(),
    created_at: new Date(nowCycles - dayMsC * 15).toISOString(),
    updated_at: new Date(nowCycles).toISOString(),
    created_by: "user-3",
    updated_by: "user-3",

    total_issues: 6,
    completed_issues: 2,
    backlog_issues: 1,
    started_issues: 2,
    unstarted_issues: 1,
    cancelled_issues: 0,
    backlog_estimate_points: 5,
    started_estimate_points: 21,
    unstarted_estimate_points: 5,
    cancelled_estimate_points: 0,
    total_estimate_points: 52,
    completed_estimate_points: 21,
  },
];

export const _ws1Detail = { id: "ws-1", name: "Flow 开发组", slug: "flow-dev", logo_url: "", logo_props: {} };
export const _proj1Detail = {
  id: "proj-1",
  identifier: "FF",
  name: "Flow 前端",
  cover_image: "",
  description: null,
  emoji: null,
  icon_prop: null,
};
export const _user1Detail = {
  id: "user-1",
  first_name: "我",
  last_name: "",
  avatar: "",
  is_bot: false,
  display_name: "我",
};
export const _user2Detail = {
  id: "user-2",
  first_name: "李四",
  last_name: "",
  avatar: "",
  is_bot: false,
  display_name: "李四",
};

// ---------------------------------------------------------------------------
// Pages
// ---------------------------------------------------------------------------

export const MOCK_PAGES: TPage[] = [
  {
    id: "page-1",
    name: "项目计划书",
    description_html: "<p>Flow 项目整体计划与里程碑安排。</p>",
    description_json: {},
    access: EPageAccess.PUBLIC,
    is_favorite: true,
    is_locked: false,
    archived_at: null,
    owned_by: "user-1",
    workspace: "ws-1",
    color: "#3b82f6",
    logo_props: { in_use: "emoji", emoji: { value: "📋" } },
    label_ids: [],
    created_at: new Date("2026-06-20T10:00:00Z"),
    updated_at: new Date("2026-06-28T14:30:00Z"),
    created_by: "user-1",
    updated_by: "user-1",
    deleted_at: undefined,
  },
  {
    id: "page-2",
    name: "API 设计文档",
    description_html: "<p>后端 API 接口设计与数据流说明。</p>",
    description_json: {},
    access: EPageAccess.PUBLIC,
    is_favorite: true,
    is_locked: false,
    archived_at: null,
    owned_by: "user-2",
    workspace: "ws-1",
    color: "#10b981",
    logo_props: { in_use: "emoji", emoji: { value: "🔌" } },
    label_ids: [],
    created_at: new Date("2026-06-18T08:00:00Z"),
    updated_at: new Date("2026-06-27T16:00:00Z"),
    created_by: "user-2",
    updated_by: "user-2",
    deleted_at: undefined,
  },
  {
    id: "page-3",
    name: "设计规范",
    description_html: "<p>UI 组件库与设计系统使用规范。</p>",
    description_json: {},
    access: EPageAccess.PRIVATE,
    is_favorite: false,
    is_locked: true,
    archived_at: null,
    owned_by: "user-1",
    workspace: "ws-1",
    color: "#8b5cf6",
    logo_props: { in_use: "emoji", emoji: { value: "🎨" } },
    label_ids: [],
    created_at: new Date("2026-06-15T09:00:00Z"),
    updated_at: new Date("2026-06-25T11:00:00Z"),
    created_by: "user-1",
    updated_by: "user-1",
    deleted_at: undefined,
  },
  {
    id: "page-4",
    name: "会议纪要 — 迭代评审",
    description_html: "<p>2026-06-24 迭代评审会议记录。</p>",
    description_json: {},
    access: EPageAccess.PUBLIC,
    is_favorite: false,
    is_locked: false,
    archived_at: new Date("2026-06-29T10:00:00Z").toISOString(),
    owned_by: "user-1",
    workspace: "ws-1",
    color: "#f59e0b",
    logo_props: { in_use: "emoji", emoji: { value: "📝" } },
    label_ids: [],
    created_at: new Date("2026-06-24T14:00:00Z"),
    updated_at: new Date("2026-06-29T10:00:00Z"),
    created_by: "user-1",
    updated_by: "user-1",
    deleted_at: undefined,
  },
  {
    id: "page-5",
    name: "团队 OKR",
    description_html: "<p>Q3 团队目标与关键结果。</p>",
    description_json: {},
    access: EPageAccess.PRIVATE,
    is_favorite: true,
    is_locked: false,
    archived_at: null,
    owned_by: "user-2",
    workspace: "ws-1",
    color: "#ef4444",
    logo_props: { in_use: "emoji", emoji: { value: "🎯" } },
    label_ids: [],
    created_at: new Date("2026-06-10T08:00:00Z"),
    updated_at: new Date("2026-06-22T09:00:00Z"),
    created_by: "user-2",
    updated_by: "user-2",
    deleted_at: undefined,
  },
  {
    id: "page-6",
    name: "测试策略文档",
    description_html: "<p>单元测试、集成测试与 E2E 测试策略。</p>",
    description_json: {},
    access: EPageAccess.PUBLIC,
    is_favorite: false,
    is_locked: false,
    archived_at: null,
    owned_by: "user-3",
    workspace: "ws-1",
    color: "#06b6d4",
    logo_props: { in_use: "emoji", emoji: { value: "🧪" } },
    label_ids: [],
    created_at: new Date("2026-06-12T10:00:00Z"),
    updated_at: new Date("2026-06-20T15:00:00Z"),
    created_by: "user-3",
    updated_by: "user-3",
    deleted_at: undefined,
  },
  {
    id: "page-7",
    name: "旧版部署文档",
    description_html: "<p>已废弃的部署流程说明。</p>",
    description_json: {},
    access: EPageAccess.PUBLIC,
    is_favorite: false,
    is_locked: false,
    archived_at: new Date("2026-06-15T08:00:00Z").toISOString(),
    owned_by: "user-3",
    workspace: "ws-1",
    color: "#6b7280",
    logo_props: { in_use: "emoji", emoji: { value: "📦" } },
    label_ids: [],
    created_at: new Date("2026-06-01T08:00:00Z"),
    updated_at: new Date("2026-06-15T08:00:00Z"),
    created_by: "user-3",
    updated_by: "user-3",
    deleted_at: undefined,
  },
];

// ---------------------------------------------------------------------------
// Notifications (per D-P20-07: mock data for NOTI-01, NOTI-03, NOTI-04)
// ---------------------------------------------------------------------------

const notifDayMs = 86400 * 1000;
const notifNow = Date.now();

export const MOCK_NOTIFICATIONS: TNotification[] = [
  {
    id: "notif-1",
    title: "更新了优先级",
    data: {
      issue: {
        id: "issue-1",
        sequence_id: 1,
        identifier: "FF-1",
        name: "实现用户登录页面 UI",
        state_name: "待办",
        state_group: "backlog",
      },
      issue_activity: {
        id: "iact-3",
        actor: "user-1",
        field: "priority",
        issue_comment: undefined,
        verb: "updated",
        new_value: "high",
        old_value: "medium",
      },
    },
    entity_identifier: "issue-1",
    entity_name: "FF-1",
    message_html: undefined,
    message: undefined,
    message_stripped: undefined,
    sender: undefined,
    receiver: undefined,
    triggered_by: "user-1",
    triggered_by_details: MOCK_MEMBERS["ws-1"]?.[0]?.member,
    read_at: undefined,
    archived_at: undefined,
    snoozed_till: undefined,
    is_inbox_issue: false,
    is_mentioned_notification: false,
    workspace: "ws-1",
    project: "proj-1",
    created_at: new Date(notifNow).toISOString(),
    updated_at: new Date(notifNow).toISOString(),
    created_by: "user-1",
    updated_by: "user-1",
  },
  {
    id: "notif-2",
    title: "更新了状态",
    data: {
      issue: {
        id: "issue-1",
        sequence_id: 1,
        identifier: "FF-1",
        name: "实现用户登录页面 UI",
        state_name: "进行中",
        state_group: "started",
      },
      issue_activity: {
        id: "iact-2",
        actor: "user-2",
        field: "state",
        issue_comment: undefined,
        verb: "updated",
        new_value: "进行中",
        old_value: "待办",
      },
    },
    entity_identifier: "issue-1",
    entity_name: "FF-1",
    message_html: undefined,
    message: undefined,
    message_stripped: undefined,
    sender: undefined,
    receiver: undefined,
    triggered_by: "user-2",
    triggered_by_details: MOCK_MEMBERS["ws-1"]?.[1]?.member,
    read_at: undefined,
    archived_at: undefined,
    snoozed_till: undefined,
    is_inbox_issue: false,
    is_mentioned_notification: false,
    workspace: "ws-1",
    project: "proj-1",
    created_at: new Date(notifNow - notifDayMs * 1).toISOString(),
    updated_at: new Date(notifNow - notifDayMs * 1).toISOString(),
    created_by: "user-2",
    updated_by: "user-2",
  },
  {
    id: "notif-3",
    title: "分配了 Issue",
    data: {
      issue: {
        id: "issue-1",
        sequence_id: 1,
        identifier: "FF-1",
        name: "实现用户登录页面 UI",
        state_name: "待办",
        state_group: "backlog",
      },
      issue_activity: {
        id: "iact-5",
        actor: "user-3",
        field: "assignee",
        issue_comment: undefined,
        verb: "updated",
        new_value: "user-3",
        old_value: "",
      },
    },
    entity_identifier: "issue-1",
    entity_name: "FF-1",
    message_html: undefined,
    message: undefined,
    message_stripped: undefined,
    sender: undefined,
    receiver: undefined,
    triggered_by: "user-3",
    triggered_by_details: MOCK_MEMBERS["ws-1"]?.[2]?.member,
    read_at: new Date(notifNow - notifDayMs * 0.5).toISOString(),
    archived_at: undefined,
    snoozed_till: undefined,
    is_inbox_issue: false,
    is_mentioned_notification: false,
    workspace: "ws-1",
    project: "proj-1",
    created_at: new Date(notifNow - notifDayMs * 2).toISOString(),
    updated_at: new Date(notifNow - notifDayMs * 2).toISOString(),
    created_by: "user-3",
    updated_by: "user-3",
  },
  {
    id: "notif-4",
    title: "更新了描述",
    data: {
      issue: {
        id: "issue-1",
        sequence_id: 1,
        identifier: "FF-1",
        name: "实现用户登录页面 UI",
        state_name: "进行中",
        state_group: "started",
      },
      issue_activity: {
        id: "iact-4",
        actor: "user-2",
        field: "description",
        issue_comment: undefined,
        verb: "updated",
        new_value: undefined,
        old_value: undefined,
      },
    },
    entity_identifier: "issue-1",
    entity_name: "FF-1",
    message_html: undefined,
    message: undefined,
    message_stripped: undefined,
    sender: undefined,
    receiver: undefined,
    triggered_by: "user-2",
    triggered_by_details: MOCK_MEMBERS["ws-1"]?.[1]?.member,
    read_at: new Date(notifNow - notifDayMs * 0.3).toISOString(),
    archived_at: undefined,
    snoozed_till: undefined,
    is_inbox_issue: false,
    is_mentioned_notification: false,
    workspace: "ws-1",
    project: "proj-1",
    created_at: new Date(notifNow - notifDayMs * 3).toISOString(),
    updated_at: new Date(notifNow - notifDayMs * 3).toISOString(),
    created_by: "user-2",
    updated_by: "user-2",
  },
  {
    id: "notif-5",
    title: "创建了 Issue",
    data: {
      issue: {
        id: "issue-8",
        sequence_id: 1,
        identifier: "FA-1",
        name: "设计 Issue 数据模型",
        state_name: "测试中",
        state_group: "started",
      },
      issue_activity: {
        id: "iact-6",
        actor: "user-1",
        field: "name",
        issue_comment: undefined,
        verb: "created",
        new_value: undefined,
        old_value: undefined,
      },
    },
    entity_identifier: "issue-8",
    entity_name: "FA-1",
    message_html: undefined,
    message: undefined,
    message_stripped: undefined,
    sender: undefined,
    receiver: undefined,
    triggered_by: "user-1",
    triggered_by_details: MOCK_MEMBERS["ws-1"]?.[0]?.member,
    read_at: undefined,
    archived_at: undefined,
    snoozed_till: undefined,
    is_inbox_issue: false,
    is_mentioned_notification: false,
    workspace: "ws-1",
    project: "proj-2",
    created_at: new Date(notifNow - notifDayMs * 5).toISOString(),
    updated_at: new Date(notifNow - notifDayMs * 5).toISOString(),
    created_by: "user-1",
    updated_by: "user-1",
  },
  {
    id: "notif-6",
    title: "修改了标题",
    data: {
      issue: {
        id: "issue-5",
        sequence_id: 5,
        identifier: "FF-5",
        name: "添加暗色模式支持",
        state_name: "进行中",
        state_group: "started",
      },
      issue_activity: {
        id: "iact-8",
        actor: "user-1",
        field: "name",
        issue_comment: undefined,
        verb: "created",
        new_value: undefined,
        old_value: undefined,
      },
    },
    entity_identifier: "issue-5",
    entity_name: "FF-5",
    message_html: undefined,
    message: undefined,
    message_stripped: undefined,
    sender: undefined,
    receiver: undefined,
    triggered_by: "user-1",
    triggered_by_details: MOCK_MEMBERS["ws-1"]?.[0]?.member,
    read_at: undefined,
    archived_at: undefined,
    snoozed_till: undefined,
    is_inbox_issue: false,
    is_mentioned_notification: false,
    workspace: "ws-1",
    project: "proj-1",
    created_at: new Date(notifNow - notifDayMs * 7).toISOString(),
    updated_at: new Date(notifNow - notifDayMs * 7).toISOString(),
    created_by: "user-1",
    updated_by: "user-1",
  },
];

export const MOCK_UNREAD_COUNT: TUnreadNotificationsCount = {
  total_unread_notifications_count: 3,
  mention_unread_notifications_count: 0,
};
