<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>YH.Modules.Page</RootNamespace>
        <AssemblyName>YH.Modules.Page</AssemblyName>
        <NoWarn>$(NoWarn);CA1027;CA1031;CA1056;CA1716;CA1812;S1135;S125;S2094;S3267;S1144</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\BuildingBlocks\Caching\Caching.csproj" />
        <ProjectReference Include="..\..\..\BuildingBlocks\Core\Core.csproj" />
        <ProjectReference Include="..\..\..\BuildingBlocks\Persistence\Persistence.csproj" />
        <ProjectReference Include="..\..\..\BuildingBlocks\Web\Web.csproj" />
        <ProjectReference Include="..\Modules.Page.Contracts\Modules.Page.Contracts.csproj" />
        <ProjectReference Include="..\..\Identity\Modules.Identity.Contracts\Modules.Identity.Contracts.csproj" />
        <ProjectReference Include="..\..\Workspace\Modules.Workspace.Contracts\Modules.Workspace.Contracts.csproj" />
        <ProjectReference Include="..\..\Workspace\Modules.Workspace\Modules.Workspace.csproj" />
    </ItemGroup>

</Project>