// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using YH.Modules.View.Data;

#nullable disable

namespace YH.Flow.Migrations.PostgreSQL.Views
{
    [DbContext(typeof(ViewDbContext))]
    partial class ViewDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("YH.Modules.View.Domain.View", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Access")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTimeOffset?>("DeletedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DisplayFilters")
                        .HasColumnType("jsonb");

                    b.Property<string>("DisplayProperties")
                        .HasColumnType("jsonb");

                    b.Property<string>("Filters")
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTimeOffset?>("LastModifiedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LogoProps")
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("OwnedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Query")
                        .HasColumnType("jsonb");

                    b.Property<string>("RichFilters")
                        .HasColumnType("jsonb");

                    b.Property<double>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(65535.0);

                    b.HasKey("Id");

                    b.HasIndex("ArchivedAt")
                        .HasDatabaseName("IX_Views_ArchivedAt");

                    b.HasIndex("OwnedBy")
                        .HasDatabaseName("IX_Views_OwnedBy");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("IX_Views_ProjectId");

                    b.HasIndex("ProjectId", "SortOrder")
                        .HasDatabaseName("IX_Views_Project_SortOrder");

                    b.ToTable("Views", "yhschema.View");
                });

            modelBuilder.Entity("YH.Modules.View.Domain.ViewFavorite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTimeOffset?>("DeletedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("ViewId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ViewId")
                        .HasDatabaseName("IX_ViewFavorites_ViewId");

                    b.HasIndex("TenantId", "ViewId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_ViewFavorites_Tenant_View_User")
                        .HasFilter("[DeletedOnUtc] IS NULL");

                    b.ToTable("ViewFavorites", "yhschema.View");

                    b.HasAnnotation("Finbuckle:MultiTenant", true);
                });
#pragma warning restore 612, 618
        }
    }
}
